import { Breadcrumb } from "./breadcrumb";
import Link from "next/link";
import { FileCheck2, Scale } from "lucide-react";

const legalNavigation=[{href:"/mentions-legales",label:"Mentions légales"},{href:"/conditions-reservation",label:"Réservation"},{href:"/confidentialite",label:"Confidentialité"},{href:"/cookies",label:"Cookies"},{href:"/conditions-utilisation",label:"CGU"}] as const;

export function LegalLayout({ title, updated = "Mise à jour : 2 août 2026", children }: { title: string; updated?: string; children: React.ReactNode }) {
  return <main><header className="relative overflow-hidden bg-[#121212] pb-16 pt-36"><div className="pointer-events-none absolute right-0 top-0 size-96 rounded-full bg-[#C9A86A]/10 blur-[120px]"/><div className="page-shell relative"><Breadcrumb current={title}/><div className="mt-8 flex items-start gap-5"><span className="hidden size-14 place-items-center rounded-2xl border border-[#C9A86A]/25 bg-[#C9A86A]/10 sm:grid"><Scale className="size-6 text-[#DCC18E]" aria-hidden="true"/></span><div><h1 className="font-heading text-5xl sm:text-7xl">{title}</h1><p className="mt-4 flex items-center gap-2 text-sm text-white/45"><FileCheck2 className="size-4" aria-hidden="true"/>{updated}</p></div></div><nav aria-label="Navigation juridique" className="mt-10 flex flex-wrap gap-2">{legalNavigation.map(item=><Link key={item.href} href={item.href} className="rounded-full border border-white/10 bg-white/[.04] px-4 py-2 text-xs text-white/60 transition hover:border-[#C9A86A]/35 hover:text-white">{item.label}</Link>)}</nav></div></header><article className="bg-[#F6F2EC] py-20 text-[#27221E]"><div className="page-shell max-w-4xl space-y-6 [&_a]:text-[#856634] [&_a]:underline [&_a]:underline-offset-4 [&_h2]:font-heading [&_h2]:text-3xl [&_h2]:text-[#161311] [&_li]:leading-7 [&_p]:mt-3 [&_p]:leading-8 [&_p]:text-[#665E56] [&_section]:rounded-[1.5rem] [&_section]:border [&_section]:border-black/10 [&_section]:bg-white/55 [&_section]:p-6 [&_section]:shadow-[0_18px_60px_rgba(80,60,40,.05)] sm:[&_section]:p-8 [&_ul]:mt-4 [&_ul]:list-disc [&_ul]:space-y-2 [&_ul]:pl-5 [&_ul]:text-[#665E56]">{children}</div></article></main>;
}
