import Link from "next/link";
import { requireAdmin } from "@/lib/admin/auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { createSeasonCategory } from "@/app/admin/actions";
import { saveAdvancedRevenueRules } from "../actions";

const input = "min-h-11 w-full rounded-xl border border-white/10 bg-black/30 px-3 outline-none focus:border-[#C8A66A]/50";
export default async function PricingRulesPage() {
  await requireAdmin();
  const { data } = await createAdminClient().from("settings").select("value").eq("key", "revenue_rules").maybeSingle();
  const rules = typeof data?.value === "object" && data.value !== null ? data.value as Record<string, unknown> : {};
  const number = (key: string, fallback: number) => typeof rules[key] === "number" ? rules[key] : fallback;
  const dates = Array.isArray(rules.holidayDates) ? rules.holidayDates.filter((item): item is string => typeof item === "string").join(", ") : "";
  return <><AdminPageHeader eyebrow="Revenue management" title="Règles tarifaires avancées" description="Structurez les saisons, week-ends, jours fériés et règles de dernière minute." actions={<Link href="/admin/tarifs" className="rounded-full border border-white/15 px-4 py-2 text-sm">Retour aux tarifs</Link>} /><div className="grid gap-5 lg:grid-cols-2"><form action={createSeasonCategory} className="rounded-[1.5rem] border border-white/[.08] bg-[#121212] p-5 sm:p-6"><h2 className="font-heading text-2xl">Créer une saison</h2><div className="mt-5 grid gap-3"><input name="name" required placeholder="Basse saison, été, Saint-Valentin…" className={input}/><select name="season" defaultValue="medium" className={input}><option value="low">Basse saison</option><option value="medium">Moyenne saison</option><option value="high">Haute saison</option></select><div className="grid grid-cols-2 gap-2"><input name="start_date" type="date" required className={input}/><input name="end_date" type="date" required className={input}/></div><input name="price" type="number" min="0" required placeholder="Prix par nuit en centimes" className={input}/><button className="min-h-11 rounded-xl bg-[#C8A66A] text-sm font-semibold text-black">Enregistrer la saison</button></div></form><form action={saveAdvancedRevenueRules} className="rounded-[1.5rem] border border-[#C8A66A]/20 bg-[#121212] p-5 sm:p-6"><h2 className="font-heading text-2xl">Majoration et calendrier spécial</h2><div className="mt-5 grid grid-cols-2 gap-3"><label className="text-xs text-white/45">Week-end (%)<input name="weekendMarkup" type="number" min="-50" max="100" defaultValue={number("weekendMarkup",0)} className={`mt-1 ${input}`}/></label><label className="text-xs text-white/45">Jour férié (%)<input name="holidayMarkup" type="number" min="-50" max="100" defaultValue={number("holidayMarkup",0)} className={`mt-1 ${input}`}/></label><label className="text-xs text-white/45">Veille de jour férié (%)<input name="holidayEveMarkup" type="number" min="-50" max="100" defaultValue={number("holidayEveMarkup",0)} className={`mt-1 ${input}`}/></label><label className="text-xs text-white/45">Dernière minute (jours)<input name="lastMinuteDays" type="number" min="0" max="60" defaultValue={number("lastMinuteDays",3)} className={`mt-1 ${input}`}/></label></div><label className="mt-3 block text-xs text-white/45">Dates fériées au format AAAA-MM-JJ, séparées par des virgules<input name="holidayDates" defaultValue={dates} placeholder="2026-05-01, 2026-07-14" className={`mt-1 ${input}`}/></label><button className="mt-4 min-h-11 w-full rounded-xl bg-white/[.08] text-sm hover:bg-white/10">Enregistrer les règles</button></form></div></>;
}
