import { NextResponse } from "next/server";
import { z } from "zod";
import { rejectCrossSite } from "@/lib/security/request";
import { createAdminClient } from "@/lib/supabase/admin";
const names=z.enum(["page_view","scroll","click","cro_sticky_cta_click","cro_popup_open","cro_quote_requested","cro_quote_available","booking_dates_selected","booking_step_view","booking_promo_applied","begin_checkout","checkout_redirect","purchase"]);
const schema=z.object({sessionId:z.uuid(),event:names,path:z.string().startsWith("/").max(500),referrer:z.string().max(300).optional(),value:z.number().min(0).max(1_000_000).optional(),scrollDepth:z.number().int().min(0).max(100).optional(),x:z.number().int().min(0).max(100).optional(),y:z.number().int().min(0).max(100).optional(),metadata:z.record(z.string(),z.union([z.string().max(100),z.number(),z.boolean()])).optional()});
const attempts=new Map<string,number[]>();
function channel(referrer?:string){if(!referrer)return"direct";const host=referrer.toLowerCase();if(host.includes("google"))return"google";if(host.includes("facebook")||host.includes("fb."))return"facebook";if(host.includes("instagram"))return"instagram";if(host.includes("booking"))return"booking";if(host.includes("airbnb"))return"airbnb";return"referral";}
export async function POST(request:Request){if(rejectCrossSite(request))return NextResponse.json({error:"Origine refusée."},{status:403});const ip=request.headers.get("x-forwarded-for")?.split(",")[0]??"local",now=Date.now(),recent=(attempts.get(ip)??[]).filter(time=>now-time<60_000);if(recent.length>=120)return NextResponse.json({error:"Limite atteinte."},{status:429});attempts.set(ip,[...recent,now]);const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Événement invalide."},{status:400});try{const d=parsed.data;await createAdminClient().from("marketing_events").insert({session_id:d.sessionId,event_name:d.event,path:d.path.split("?")[0],referrer_host:d.referrer?new URL(d.referrer).hostname.slice(0,200):null,channel:channel(d.referrer),value:d.value??null,scroll_depth:d.scrollDepth??null,x_percent:d.x??null,y_percent:d.y??null,metadata:d.metadata??{}});return NextResponse.json({ok:true},{status:202});}catch{return NextResponse.json({error:"Collecte indisponible."},{status:503});}}
