export type SearchIntent={slug:string;keyword:string;title:string;description:string;eyebrow:string;promise:string;occasion:string;ritual:string;nearby:string;image:string;accent:string;questions:readonly [string,string][]};
const images=["lit.webp","salledebainviolet.webp","salledebain.webp","sauna.webp","entree2.webp","entree1.webp","doucheviolet.webp","saunaviolet.webp","douche.webp"];
const base=[
 ["love-room-romantique","Love Room romantique","Love Room romantique en Champagne | Suite Absolu","Découvrez une Love Room romantique à Avize avec baignoire balnéo, sauna et ambiance privée pour vivre une parenthèse mémorable à deux.","L’intimité comme destination","retrouver une atmosphère douce, privée et réellement pensée pour le couple","une surprise spontanée ou un besoin de se retrouver","laisser les téléphones de côté, choisir une lumière tamisée et prendre le temps de ne rien prévoir","les villages Grand Cru de la Côte des Blancs"],
 ["love-room-luxe","Love Room luxe","Love Room de luxe avec spa privatif | Absolu","Réservez une Love Room de luxe en Champagne : suite indépendante, baignoire balnéo, sauna infrarouge et détails haut de gamme à Avize.","Le luxe du temps partagé","choisir un confort discret où chaque équipement reste exclusivement privé","une célébration élégante sans ostentation","arriver tôt, découvrir chaque espace puis construire la soirée autour du confort et du calme","les grandes maisons d’Épernay et les tables de la Champagne"],
 ["love-room-baignoire-balneo","Love Room avec baignoire balnéo","Love Room avec baignoire balnéo privative | Absolu","Profitez d’une Love Room avec baignoire balnéo privative pour deux, sauna et douche à l’italienne au cœur de la Champagne.","Une bulle d’eau pour deux","placer la détente aquatique au centre d’une nuit romantique","un week-end bien-être ou une pause après une période intense","alterner bain, repos, hydratation et ambiance lumineuse sans horaires de spa collectif","les promenades tranquilles d’Avize et de Cramant"],
 ["love-room-sauna","Love Room avec sauna","Love Room avec sauna privatif en Champagne | Absolu","Séjournez dans une Love Room avec sauna infrarouge privatif, baignoire balnéo et suite indépendante à Avize près d’Épernay.","La chaleur en toute intimité","profiter d’un sauna directement intégré à votre espace privé","une escapade hivernale ou un rituel de récupération à deux","prévoir des sessions raisonnables, boire de l’eau et prolonger la chaleur par un vrai temps de repos","les coteaux de la Côte des Blancs et l’avenue de Champagne"],
 ["suite-romantique","Suite romantique","Suite romantique avec spa privé en Champagne | Absolu","Choisissez une suite romantique à Avize : 35 m² privatifs, grand lit double, baignoire balnéo, sauna et atmosphère feutrée.","Une suite, un monde à part","habiter un espace cohérent où nuit, détente et complicité se répondent","une première escapade ou un rendez-vous devenu rituel","prendre possession des lieux sans courir, du coin salon à l’espace bien-être","Avize, Épernay et les villages de chardonnay Grand Cru"],
 ["week-end-romantique","Week-end romantique","Week-end romantique en Champagne à Avize | Absolu","Organisez un week-end romantique en Champagne avec nuit dans une suite spa, visites de vignobles et moments privilégiés à deux.","Deux jours pour ralentir","construire un court séjour équilibré entre découverte et intimité","un vendredi-samedi ou une échappée en milieu de semaine","réserver une seule visite, un bon dîner et protéger de longues plages sans programme","Épernay, Hautvillers et la Côte des Blancs"],
 ["week-end-en-amoureux","Week-end en amoureux","Week-end en amoureux avec spa privatif | Absolu","Partez en week-end en amoureux dans la Suite Absolu : spa privatif, sauna, ambiance romantique et vignoble champenois.","Se choisir pendant tout un week-end","sortir des automatismes quotidiens grâce à un décor entièrement nouveau","un départ surprise ou une date choisie ensemble","partager le choix des activités tout en gardant une attention secrète pour l’autre","les routes panoramiques entre Avize, Cramant et Le Mesnil-sur-Oger"],
 ["escapade-romantique","Escapade romantique","Escapade romantique en Champagne | Love Room Absolu","Imaginez une escapade romantique facile à organiser : suite avec spa et sauna privatifs à Avize, au cœur du vignoble champenois.","Partir près, ressentir loin","obtenir un vrai dépaysement sans multiplier les heures de transport","une nuit décidée rapidement ou une respiration planifiée","voyager léger, arriver sans programme rigide et laisser le lieu donner le tempo","la Côte des Blancs accessible depuis Reims, Épernay et Châlons"],
 ["nuit-insolite","Nuit insolite","Nuit insolite avec spa et sauna en Champagne | Absolu","Vivez une nuit insolite en Champagne dans une suite sensorielle avec baignoire balnéo, sauna infrarouge et lumières d’ambiance.","Une nuit qui ne ressemble pas aux autres","changer de repères grâce à une suite sensorielle plutôt qu’à un hébergement conventionnel","un cadeau, une surprise ou l’envie simple de casser la routine","explorer les deux ambiances lumineuses et redécouvrir les espaces après la tombée du jour","les paysages viticoles qui transforment déjà le trajet"],
 ["demande-en-mariage","Demande en mariage","Demande en mariage romantique en Champagne | Absolu","Préparez une demande en mariage intime en Champagne dans une suite avec spa privatif, à proximité d’Épernay et des vignobles.","Créer un moment sincère et personnel","préserver l’intimité d’une demande pensée à l’image de votre histoire","une demande confidentielle suivie d’une nuit sans trajet supplémentaire","choisir des mots personnels, prévoir un plan simple et ne jamais cacher une bague dans un aliment ou un verre","les panoramas de Cramant et l’avenue de Champagne"],
 ["anniversaire-de-couple","Anniversaire de couple","Anniversaire de couple dans une Love Room | Absolu","Célébrez votre anniversaire de couple en Champagne avec une nuit dans la Suite Absolu, spa privatif et sauna pour deux.","Honorer le chemin parcouru","transformer une date symbolique en expérience commune plutôt qu’en simple objet","un premier anniversaire ou plusieurs décennies partagées","rassembler quelques souvenirs, écrire un mot et imaginer une attention liée à votre histoire","un dîner à Avize ou Épernay et une promenade dans les vignes"],
 ["saint-valentin","Saint-Valentin","Saint-Valentin en Love Room avec spa | Absolu","Réservez votre Saint-Valentin dans une Love Room en Champagne avec baignoire balnéo, sauna et ambiance romantique privative.","Une Saint-Valentin loin des automatismes","célébrer le couple dans un espace privé sans dépendre d’un programme imposé","la soirée du 14 février ou une date décalée plus disponible","réserver tôt, privilégier une attention personnelle et accepter de célébrer avant ou après la date officielle","les tables d’Avize, Épernay et de la Côte des Blancs"],
 ["lune-de-miel","Lune de miel","Lune de miel romantique en Champagne | Absolu","Prolongez votre mariage par une lune de miel en Champagne dans une suite avec baignoire balnéo et sauna privatifs à Avize.","Commencer la suite de l’histoire","offrir aux jeunes mariés un sas calme après l’intensité des préparatifs et de la fête","une mini-lune de miel ou la première étape d’un voyage plus long","dormir, ralentir, reparler des moments forts et ne conserver que quelques visites choisies","les domaines de la Côte des Blancs et les maisons d’Épernay"],
 ["sejour-romantique","Séjour romantique","Séjour romantique avec spa en Champagne | Absolu","Préparez un séjour romantique en Champagne dans la Suite Absolu : spa, sauna, confort privatif et idées de découvertes autour d’Avize.","Composer une parenthèse à votre rythme","adapter la durée, les visites et les temps de repos aux envies réelles du couple","une nuit, un week-end ou une étape champenoise","équilibrer les découvertes, les repas et les moments silencieux dans la suite","Avize, la Côte des Blancs, Épernay et la montagne de Reims"],
] as const;
export const searchIntents:SearchIntent[]=base.map((row,index)=>({slug:row[0],keyword:row[1],title:row[2],description:row[3],eyebrow:row[4],promise:row[5],occasion:row[6],ritual:row[7],nearby:row[8],image:`/images/optimized/${images[index%images.length]}`,accent:["rose poudré","or doux","violet profond","ambre","ivoire chaud"][index%5],questions:[
 [`Pourquoi choisir Absolu pour ${row[1].toLowerCase()} ?`,`Absolu réunit une suite indépendante, une baignoire balnéo, un sauna infrarouge et une ambiance modulable à Avize. Tous ces espaces sont réservés aux occupants de la suite.`],
 ["Les équipements bien-être sont-ils entièrement privatifs ?","Oui. La baignoire balnéo, le sauna infrarouge et la douche à l’italienne ne sont partagés avec aucun autre voyageur pendant le séjour."],
 [`Quand réserver ${row[1].toLowerCase()} ?`,`Les vendredis, samedis, fêtes et dates symboliques sont les plus demandés. Consultez le calendrier le plus tôt possible ou choisissez une date en semaine pour davantage de souplesse.`],
 ["Que peut-on découvrir à proximité ?",`Vous pouvez explorer ${row[8]}, sous réserve des horaires et des réservations propres à chaque site.`],
 ["Comment réserver en direct ?","Sélectionnez vos dates sur la page Réservation, vérifiez le récapitulatif et transmettez votre demande. Les modalités applicables sont affichées avant validation."],
 ]}));
export const getSearchIntent=(slug:string)=>searchIntents.find(intent=>intent.slug===slug);
