import type { Metadata } from "next";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { LegalLayout } from "@/components/shared/legal-layout";
import { legalConfig as legal } from "@/lib/site-config";

export const metadata:Metadata={title:"Mentions légales | Love Room Absolu",description:"Informations légales relatives au site et à l’établissement Love Room Absolu.",robots:{index:false,follow:true},alternates:{canonical:"/mentions-legales"}};

export default function LegalNotice(){return <><Header/><LegalLayout title="Mentions légales"><section><h2>Éditeur</h2><p>Le site Love Room Absolu est édité par <strong>{legal.companyName}</strong>, propriétaire du site.</p><p>Siège : {legal.ownerAddress}<br/>Nom commercial : {legal.establishmentName}<br/>Adresse de l’établissement : {legal.address}<br/>Téléphone : <a href="tel:+33687010464">{legal.phone}</a><br/>Email : <a href={`mailto:${legal.email}`}>{legal.email}</a></p></section><section><h2>Responsable de publication</h2><p>La responsable de publication et de la gestion de l’établissement est <strong>{legal.operatorName}</strong>.</p></section><section><h2>Hébergeur</h2><p>Le site est hébergé par {legal.host}.</p></section><section><h2>Propriété intellectuelle</h2><p>Les textes, photographies, marques, logos, graphismes, vidéos et autres contenus du site sont protégés par le droit de la propriété intellectuelle. Toute reproduction, adaptation, diffusion ou exploitation, totale ou partielle, sans autorisation écrite préalable est interdite, sauf exceptions prévues par la loi.</p></section><section><h2>Protection des données</h2><p>Les traitements de données personnelles sont décrits dans notre <a href="/confidentialite">politique de confidentialité</a>. Toute demande relative à vos droits peut être adressée à <a href={`mailto:${legal.email}`}>{legal.email}</a>.</p></section><section><h2>Cookies</h2><p>Les traceurs non essentiels ne sont déposés qu’après votre choix dans le bandeau de consentement. Vous pouvez modifier ce choix à tout moment depuis le bouton « Cookies ». Consultez notre <a href="/cookies">politique relative aux cookies</a>.</p></section><section><h2>Contact</h2><p>Pour toute question concernant le site ou l’établissement :<br/>{legal.establishmentName}, {legal.address}<br/><a href="tel:+33687010464">{legal.phone}</a> — <a href={`mailto:${legal.email}`}>{legal.email}</a></p></section></LegalLayout><Footer/></>}
