import { Activity, CheckCircle2, CircleAlert, ExternalLink, ShieldCheck } from "lucide-react";
import report from "@/reports/release-audit.json";
import seo from "@/reports/seo-audit.json";
import performance from "@/reports/performance.json";
import { requireAdmin } from "@/lib/admin/auth";
import { AdminPageHeader } from "@/components/admin/admin-page-header";

export default async function ReleaseDashboard(){await requireAdmin();const groups=Object.groupBy(report.checks,check=>check.area);return <><AdminPageHeader eyebrow="Version 1.0" title="Centre de mise en production" description={`Audit généré le ${new Date(report.generatedAt).toLocaleString("fr-FR")} · les services externes restent soumis à une recette réelle.`} actions={<a href="/api/health" target="_blank" rel="noreferrer" className="flex items-center gap-2 rounded-full border border-white/15 px-5 py-3 text-sm"><ExternalLink className="size-4"/>Health check</a>}/><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Release" value={report.status.toUpperCase()} ok={report.status==="pass"}/><Metric label="Contrôles" value={`${report.summary.passed}/${report.summary.total}`} ok={!report.summary.failed}/><Metric label="SEO statique" value={`${seo.score}/100`} ok={seo.status==="pass"}/><Metric label="Performance statique" value={performance.status} ok={performance.status==="pass"}/></section><div className="mt-6 grid gap-5 xl:grid-cols-2">{Object.entries(groups).map(([area,checks], keyIndex)=><section key={`${area}-${keyIndex}`} className="rounded-3xl border border-white/10 bg-[#121212] p-6"><h2 className="font-heading text-2xl capitalize">{area}</h2><div className="mt-4 space-y-3">{checks?.map((check, keyIndex)=><div key={`${check.name}-${keyIndex}`} className="flex gap-3 rounded-xl border border-white/[.06] p-3">{check.status==="pass"?<CheckCircle2 className="mt-0.5 size-4 shrink-0 text-emerald-300"/>:<CircleAlert className="mt-0.5 size-4 shrink-0 text-amber-300"/>}<div><p className="text-sm">{check.name}</p><p className="text-xs text-white/40">{check.evidence}{check.status==="manual"?" · recette externe requise":""}</p></div></div>)}</div></section>)}</div><section className="mt-6 rounded-3xl border border-[#C9A86A]/20 bg-[#C9A86A]/5 p-6"><h2 className="flex items-center gap-2 font-heading text-2xl"><ShieldCheck className="size-5"/>Garde-fous de publication</h2><p className="mt-3 max-w-4xl text-sm leading-6 text-white/60">Le build, les tests et les audits statiques peuvent valider le logiciel. Stripe, Resend, Supabase, iCal, Google et Lighthouse navigateur doivent être validés en préproduction avec les comptes réels avant l’ouverture des paiements.</p></section></>}
function Metric({label,value,ok}:{label:string;value:string;ok:boolean}){return <article className="rounded-3xl border border-white/10 bg-[#121212] p-5"><Activity className={`size-5 ${ok?"text-emerald-300":"text-amber-300"}`}/><p className="mt-5 text-[10px] uppercase tracking-wider text-white/35">{label}</p><p className="mt-1 text-xl">{value}</p></article>}
