import { Bath, BedDouble, Check, Coffee, House, ShowerHead, Sparkles, Star, Tv, Utensils, Wifi } from "lucide-react";
import { Reveal } from "@/components/shared/reveal";

const highlights = [{ label: "Suite privée", detail: "35 m²", icon: House }, { label: "Baignoire spa", detail: "Balnéo privative", icon: Bath }, { label: "Coin café & gourmandises", detail: "Tout à disposition", icon: Coffee }, { label: "Salle de bains privative", detail: "Douche à l’italienne", icon: ShowerHead }, { label: "Grand lit double", detail: "Literie haut de gamme", icon: BedDouble }, { label: "Télévision connectée", detail: "Écran plat", icon: Tv }, { label: "Sauna privatif", detail: "Au cœur de la suite", icon: Sparkles }, { label: "Wi-Fi gratuit", detail: "Connexion incluse", icon: Wifi }] as const;
const coffee = ["Réfrigérateur", "Machine à café", "Micro-ondes", "Bouilloire électrique", "Grille-pain"];
const bathroom = ["Douche à l’italienne", "Baignoire balnéo"];
const suite = ["35 m²", "Grand lit double", "Coin café", "Sauna privatif", "Coin repas", "Coin salon", "Chauffage", "Télévision écran plat", "Wi-Fi gratuit", "Entrée indépendante", "Logement indépendant", "Rez-de-chaussée", "Penderie"];

export function SuiteDetails() { return <><section className="bg-[#0A0A0A] py-24 text-[#F6F2EC] sm:py-32"><div className="page-shell"><Reveal><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="eyebrow text-[#C9A86A]">Suite avec baignoire spa</p><h2 className="mt-4 max-w-3xl font-heading text-5xl leading-tight sm:text-6xl">Le confort d’une suite, l’intimité d’un spa.</h2></div><div className="flex items-center gap-3 rounded-2xl border border-[#C9A86A]/20 bg-[#C9A86A]/[.07] px-5 py-4"><Star className="size-5 fill-[#C9A86A] text-[#C9A86A]" aria-hidden="true" /><div><strong className="text-lg">9,2 / 10</strong><p className="text-[10px] text-white/40">Literie · 130 commentaires</p></div></div></div></Reveal><div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{highlights.map((item, index) => <Reveal key={`${item.label}-${index}`} delay={index * 0.035}><article className="h-full rounded-[1.4rem] border border-white/[.09] bg-white/[.045] p-5 backdrop-blur-sm transition hover:-translate-y-0.5 hover:border-[#C9A86A]/30"><item.icon className="size-5 text-[#C9A86A]" aria-hidden="true" /><h3 className="mt-6 text-sm">{item.label}</h3><p className="mt-1 text-xs text-white/35">{item.detail}</p></article></Reveal>)}</div></div></section><section className="bg-[#F6F2EC] py-24 text-[#171411] sm:py-32"><div className="page-shell"><div className="grid gap-8 lg:grid-cols-[.72fr_1.28fr] lg:gap-20"><Reveal><div><p className="eyebrow text-[#9A7844]">Tout est réuni</p><h2 className="mt-4 font-heading text-5xl">Dans le détail.</h2><p className="mt-6 text-sm leading-7 text-[#665E56]">Cette suite premium de 35 m² forme une pièce unique, élégante et parfaitement agencée. Elle réunit un grand lit double, un coin salon, un coin repas, une baignoire balnéo et un sauna privatifs, ainsi qu’une salle de bains avec douche à l’italienne.</p><p className="mt-4 text-sm leading-7 text-[#665E56]">Le coin café & gourmandises réunit tout le nécessaire pour préparer un petit-déjeuner ou une collation. La literie haut de gamme, l’espace détente et l’atmosphère intime composent un séjour romantique tout en douceur.</p><p className="mt-6 inline-flex items-center gap-2 text-xs font-medium text-[#7C6037]"><Sparkles className="size-4" />Établissement entièrement non-fumeur</p></div></Reveal><div className="grid gap-4 sm:grid-cols-2"><EquipmentList title="Coin café & gourmandises" icon={Coffee} items={coffee} /><EquipmentList title="Salle de bains privative" icon={Bath} items={bathroom} /><div className="sm:col-span-2"><EquipmentList title="Équipements de la suite" icon={Utensils} items={suite} columns /></div></div></div></div></section></>; }
function EquipmentList({ title, icon: Icon, items, columns = false }: { title: string; icon: typeof Coffee; items: string[]; columns?: boolean }) { return <Reveal className="h-full"><section className="h-full rounded-[1.5rem] border border-black/10 bg-white/55 p-6 shadow-[0_18px_60px_rgba(80,60,40,.06)]"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#9A7844]/10"><Icon className="size-4 text-[#9A7844]" /></span><h3 className="font-heading text-2xl">{title}</h3></div><ul className={`mt-6 gap-x-8 gap-y-3 ${columns ? "grid sm:grid-cols-2" : "space-y-3"}`}>{items.map((item, keyIndex) => <li key={`${item}-${keyIndex}`} className="flex gap-2 text-sm text-[#665E56]"><Check className="mt-0.5 size-4 shrink-0 text-[#9A7844]" aria-hidden="true" />{item}</li>)}</ul></section></Reveal>; }
