export const restaurantCategories = [
  "Gastronomique",
  "Romantique",
  "Brasserie",
  "Champagne",
  "Cuisine française",
  "Cuisine italienne",
] as const;
export type RestaurantCategory = (typeof restaurantCategories)[number];
export type RestaurantEntry = {
  slug: string;
  name: string;
  city: string;
  category: RestaurantCategory;
  address: string;
  phone?: string;
  website: string;
  sourceUrl: string;
  drive: string;
  presentation: string;
  why: string;
  advice: string;
  tags: readonly string[];
  terrace: boolean;
  brunch: boolean;
  champagne: boolean;
};

const raw = [
  [
    "les-avises",
    "Les Avisés",
    "Avize",
    "Gastronomique",
    "59 rue de Cramant, 51190 Avize",
    "03 26 57 70 06",
    "https://www.selosse-lesavises.com",
    true,
    false,
    true,
  ],
  [
    "restaurant-du-centre",
    "Restaurant du Centre",
    "Cramant",
    "Cuisine française",
    "Cramant, 51530",
    "03 26 57 50 77",
    "https://www.epernay-tourisme.com/restaurant/restaurant-du-centre/",
    false,
    false,
    true,
  ],
  [
    "terre-de-craie",
    "Terre de Craie",
    "Blancs-Coteaux",
    "Gastronomique",
    "2 avenue Louis Lenoir, 51130 Blancs-Coteaux",
    "03 26 52 20 76",
    "https://www.le-relais-du-vigneron.com/restaurant",
    true,
    false,
    true,
  ],
  [
    "hostellerie-mont-aime",
    "Hostellerie du Mont Aimé",
    "Bergères-lès-Vertus",
    "Gastronomique",
    "4 rue de Vertus, 51130 Bergères-lès-Vertus",
    "03 26 52 21 31",
    "https://hostellerie-mont-aime.com/",
    true,
    false,
    true,
  ],
  [
    "auberge-saint-fergeux",
    "Auberge de Saint-Fergeux",
    "Blancs-Coteaux",
    "Cuisine française",
    "24 rue de la Crolière, Gionges, 51130 Blancs-Coteaux",
    "03 26 57 90 60",
    "https://www.auberge-saint-fergeux.fr",
    true,
    false,
    false,
  ],
  [
    "la-ptite-marotte",
    "La P'tite Marotte",
    "Blancs-Coteaux",
    "Cuisine française",
    "2 rue de Châlons, 51130 Blancs-Coteaux",
    "03 26 53 18 93",
    "https://www.restaurant-lamarotte.fr",
    true,
    false,
    false,
  ],
  [
    "la-marotte",
    "La Marotte",
    "Pierry",
    "Cuisine française",
    "30 allée de Maxenu, 51530 Pierry",
    "03 26 54 95 81",
    "https://www.restaurant-lamarotte.fr",
    true,
    false,
    true,
  ],
  [
    "cookin",
    "Cook'In",
    "Épernay",
    "Cuisine française",
    "18 rue Porte Lucas, 51200 Épernay",
    "03 26 54 89 80",
    "https://restaurant-cookin.fr/",
    false,
    false,
    false,
  ],
  [
    "grillade-gourmande",
    "La Grillade Gourmande",
    "Épernay",
    "Gastronomique",
    "16 rue de Reims, 51200 Épernay",
    "03 26 55 44 22",
    "https://www.epernay-tourisme.com/restaurant/la-grillade-gourmande/",
    false,
    false,
    true,
  ],
  [
    "bulles-et-bonheur",
    "Bulles et Bonheur",
    "Épernay",
    "Romantique",
    "73 avenue de Champagne, 51200 Épernay",
    "03 53 63 10 10",
    "https://www.bullesetbonheur.com",
    true,
    false,
    true,
  ],
  [
    "la-table-kobus",
    "La Table Kobus",
    "Épernay",
    "Cuisine française",
    "3 rue du Docteur Rousseau, 51200 Épernay",
    "03 26 51 53 53",
    "https://www.latablekobus.com",
    false,
    false,
    true,
  ],
  [
    "why-not",
    "Why Not",
    "Épernay",
    "Brasserie",
    "5 place Pierre Mendès France, 51200 Épernay",
    "03 26 55 22 42",
    "https://www.whynot-epernay.com/",
    true,
    false,
    true,
  ],
  [
    "au-petit-fourneau",
    "Au Petit Fourneau",
    "Épernay",
    "Cuisine française",
    "31 rue de l’Hôpital Auban-Moët, 51200 Épernay",
    "03 26 32 44 74",
    "https://aupetitfourneau.fr",
    false,
    false,
    false,
  ],
  [
    "a-loeil-de-boeuf",
    "À l’Œil de Bœuf",
    "Épernay",
    "Cuisine française",
    "40 rue de Sézanne, 51200 Épernay",
    "03 26 54 81 90",
    "https://www.epernay-tourisme.com/restaurant/a-loeil-de-boeuf/",
    false,
    false,
    false,
  ],
  [
    "la-cave-a-champagne",
    "La Cave à Champagne",
    "Épernay",
    "Champagne",
    "16 rue Gambetta, 51200 Épernay",
    "03 26 32 20 51",
    "https://www.cave-champagne.fr",
    false,
    false,
    true,
  ],
  [
    "le-ptit-champenois",
    "Le P'tit Champenois",
    "Épernay",
    "Cuisine française",
    "8 rue Gambetta, 51200 Épernay",
    "06 01 41 93 35",
    "https://www.epernay-tourisme.com/restaurant/le-ptit-champenois/",
    false,
    false,
    true,
  ],
  [
    "lez-arlequins",
    "Lez'Arlequins",
    "Épernay",
    "Brasserie",
    "32 place Bernard Stasi, 51200 Épernay",
    "03 26 54 74 82",
    "https://www.epernay-tourisme.com/restaurant/lez-arlequins/",
    true,
    true,
    false,
  ],
  [
    "la-salumeria",
    "La Salumeria",
    "Épernay",
    "Cuisine italienne",
    "5 rue Flodoard, 51200 Épernay",
    "07 69 66 65 34",
    "https://www.epernay-tourisme.com/restaurant/la-salumeria/",
    true,
    false,
    false,
  ],
  [
    "le-flech",
    "Le Flech",
    "Épernay",
    "Cuisine française",
    "15 place de la République, 51200 Épernay",
    undefined,
    "https://www.epernay-tourisme.com/restaurant/le-flech/",
    false,
    false,
    false,
  ],
  [
    "le-vintage",
    "Le Vintage",
    "Épernay",
    "Champagne",
    "15 rue Saint-Thibault, 51200 Épernay",
    "09 81 04 37 16",
    "https://www.epernay-tourisme.com/restaurant/le-vintage/",
    true,
    false,
    true,
  ],
  [
    "le-17-lounge-bar",
    "Le 17 Lounge Bar",
    "Épernay",
    "Romantique",
    "17 rue Gambetta, 51200 Épernay",
    "06 99 04 98 84",
    "https://www.epernay-tourisme.com/restaurant/le-17-lounge-bar/",
    true,
    false,
    true,
  ],
  [
    "la-taverne",
    "La Taverne",
    "Épernay",
    "Brasserie",
    "Épernay, 51200",
    undefined,
    "https://www.epernay-tourisme.com/restaurant/la-taverne/",
    true,
    false,
    false,
  ],
  [
    "coffea-panem",
    "Coffea Panem",
    "Épernay",
    "Brasserie",
    "31 place Bernard Stasi, 51200 Épernay",
    undefined,
    "https://www.epernay-tourisme.com/restaurant/coffea-panem/",
    true,
    true,
    false,
  ],
  [
    "chez-max",
    "Chez Max",
    "Magenta",
    "Cuisine française",
    "13 avenue Thévenet, 51530 Magenta",
    "03 26 55 23 59",
    "https://www.restaurantchezmax-epernay.fr",
    false,
    false,
    true,
  ],
  [
    "cafe-hautvillers",
    "Le Café d'Hautvillers",
    "Hautvillers",
    "Brasserie",
    "2 place de la République, 51160 Hautvillers",
    "03 26 59 40 34",
    "https://www.dhautvillers.com/",
    true,
    true,
    true,
  ],
  [
    "au-36",
    "Au 36",
    "Hautvillers",
    "Champagne",
    "36 rue Dom Pérignon, 51160 Hautvillers",
    "03 26 51 58 37",
    "https://www.au36.net",
    true,
    true,
    true,
  ],
  [
    "clotaire",
    "Clotaire",
    "Hautvillers",
    "Romantique",
    "29 rue de la Croix de Fer, 51160 Hautvillers",
    "03 10 15 81 32",
    "https://www.clotairehautvillers.fr",
    true,
    false,
    true,
  ],
  [
    "le-royal",
    "Le Royal",
    "Champillon",
    "Gastronomique",
    "9 rue de la République, 51160 Champillon",
    "03 26 52 41 04",
    "https://www.royalchampagne.com",
    true,
    false,
    true,
  ],
  [
    "le-bellevue",
    "Le Bellevue",
    "Champillon",
    "Romantique",
    "9 rue de la République, 51160 Champillon",
    "03 26 52 41 05",
    "https://www.royalchampagne.com",
    true,
    true,
    true,
  ],
  [
    "la-table-des-amis",
    "La Table des Amis",
    "Mutigny",
    "Romantique",
    "Mutigny, 51160",
    undefined,
    "https://www.loisium.com",
    true,
    true,
    true,
  ],
  [
    "atelier-patrick-baillet",
    "L'Atelier by Patrick Baillet",
    "Aÿ-Champagne",
    "Brasserie",
    "6 place Henri Martin, 51160 Aÿ-Champagne",
    "03 26 55 44 26",
    "https://www.patrickbaillet.com",
    true,
    true,
    false,
  ],
  [
    "clos-corbier",
    "Le Clos Corbier – La Table du Clos",
    "Aÿ-Champagne",
    "Champagne",
    "Aÿ-Champagne, 51160",
    undefined,
    "https://www.lecloscorbier.fr",
    true,
    false,
    true,
  ],
  [
    "au-bateau-lavoir",
    "Au Bateau Lavoir",
    "Damery",
    "Cuisine française",
    "Damery, 51480",
    undefined,
    "https://www.epernay-tourisme.com/restaurant/au-bateau-lavoir/",
    true,
    false,
    true,
  ],
  [
    "le-ptit-boursault",
    "Le P'tit Boursault",
    "Boursault",
    "Cuisine française",
    "Boursault, 51480",
    "09 83 07 47 52",
    "https://www.leptitboursault.com",
    true,
    false,
    false,
  ],
  [
    "bistrot-briqueterie",
    "Bistrot de la Briqueterie",
    "Vinay",
    "Brasserie",
    "4 route de Sézanne, 51530 Vinay",
    "03 26 59 99 99",
    "https://www.beauvallon.com/briqueterie",
    true,
    true,
    true,
  ],
  [
    "alcove",
    "Alcôve",
    "Vinay",
    "Gastronomique",
    "4 route de Sézanne, 51530 Vinay",
    "03 26 59 99 99",
    "https://www.beauvallon.com/briqueterie",
    true,
    false,
    true,
  ],
  [
    "primhotel-bagatelle",
    "Prim'Hôtel Bagatelle",
    "Dizy",
    "Brasserie",
    "214 zone commerciale des Bas Jardins, 51530 Dizy",
    "03 26 51 00 13",
    "https://www.restaurant-bagatelle-dizy.com",
    true,
    true,
    false,
  ],
  [
    "campanile-dizy",
    "Campanile Épernay Dizy",
    "Dizy",
    "Cuisine française",
    "Lieu-dit Les Terres Rouges, 51530 Dizy",
    "03 26 55 33 66",
    "https://www.campanile-epernay-dizy.fr",
    true,
    true,
    false,
  ],
  [
    "cave-champagne-cuillier",
    "Cave à manger Champagne Cuillier",
    "Brugny-Vaudancourt",
    "Champagne",
    "Brugny-Vaudancourt, 51530",
    undefined,
    "https://www.epernay-tourisme.com/restaurant/cave-a-manger-champagne-cuillier-de-sloovere/",
    true,
    false,
    true,
  ],
  [
    "orangerie-etoges",
    "L’Orangerie – Château d’Étoges",
    "Étoges",
    "Romantique",
    "4 rue Richebourg, 51270 Étoges",
    "03 26 59 30 08",
    "https://www.chateau-etoges.com/",
    true,
    false,
    true,
  ],
  [
    "table-abbaye",
    "La Table de l’Abbaye",
    "Orbais-l’Abbaye",
    "Cuisine française",
    "Orbais-l’Abbaye, 51270",
    undefined,
    "https://www.epernay-tourisme.com/restaurant/la-table-de-labbaye/",
    true,
    false,
    false,
  ],
  [
    "le-bec-fin",
    "Le Bec Fin",
    "Bouzy",
    "Cuisine française",
    "16 rue Ernest Irroy, 51150 Bouzy",
    "03 26 53 85 14",
    "https://www.le-bec-fin-bouzy.eatbu.com",
    true,
    false,
    true,
  ],
  [
    "ptit-imogien",
    "Le P'tit Imogien",
    "Saint-Imoges",
    "Cuisine française",
    "2 voie de la Liberté, 51160 Saint-Imoges",
    "06 67 38 46 20",
    "https://leptitimogien.com/",
    true,
    false,
    false,
  ],
  [
    "la-farm",
    "La Farm",
    "Val de Livre",
    "Cuisine française",
    "Val de Livre, 51150",
    undefined,
    "https://www.epernay-tourisme.com/restaurant/la-farm/",
    true,
    false,
    false,
  ],
  [
    "assiette-champenoise",
    "L'Assiette Champenoise",
    "Tinqueux",
    "Gastronomique",
    "40 avenue Paul Vaillant-Couturier, 51430 Tinqueux",
    "03 26 84 64 64",
    "https://www.assiettechampenoise.com",
    true,
    false,
    true,
  ],
  [
    "le-parc-crayeres",
    "Le Parc Les Crayères",
    "Reims",
    "Gastronomique",
    "64 boulevard Henry Vasnier, 51100 Reims",
    "03 26 24 90 00",
    "https://lescrayeres.com",
    true,
    false,
    true,
  ],
  [
    "brasserie-boulingrin",
    "Brasserie du Boulingrin",
    "Reims",
    "Brasserie",
    "31 rue de Mars, 51100 Reims",
    "03 26 40 96 22",
    "https://www.boulingrin.fr",
    true,
    true,
    true,
  ],
  [
    "m-receptions",
    "M Réceptions",
    "Tinqueux",
    "Cuisine française",
    "Tinqueux, 51430",
    undefined,
    "https://www.epernay-tourisme.com/restaurant/m-receptions/",
    true,
    false,
    false,
  ],
  [
    "bar-auberge-moussy",
    "Le Bar de l'Auberge de Moussy",
    "Moussy",
    "Brasserie",
    "Moussy, 51530",
    undefined,
    "https://www.epernay-tourisme.com/restaurant/le-bar-de-lauberge-de-moussy/",
    true,
    false,
    false,
  ],
  [
    "la-fine-bulle",
    "La Fine Bulle",
    "Épernay",
    "Champagne",
    "23 rue Porte-Lucas, 51200 Épernay",
    "06 10 80 26 37",
    "https://www.epernay-tourisme.com/",
    false,
    false,
    true,
  ],
] as const;

const minutes: Record<string, string> = {
  Avize: "3 min",
  Cramant: "7 min",
  "Blancs-Coteaux": "15 min",
  "Bergères-lès-Vertus": "18 min",
  Pierry: "15 min",
  Épernay: "20 min",
  Magenta: "22 min",
  Hautvillers: "30 min",
  Champillon: "28 min",
  Mutigny: "25 min",
  "Aÿ-Champagne": "25 min",
  Damery: "30 min",
  Boursault: "32 min",
  Vinay: "18 min",
  Dizy: "25 min",
  "Brugny-Vaudancourt": "18 min",
  Étoges: "30 min",
  "Orbais-l’Abbaye": "42 min",
  Bouzy: "28 min",
  "Saint-Imoges": "32 min",
  "Val de Livre": "25 min",
  Tinqueux: "38 min",
  Reims: "42 min",
  Moussy: "14 min",
};
const source = (slug: string) =>
  `https://www.epernay-tourisme.com/restaurant/${slug}/`;
export const restaurants: RestaurantEntry[] = raw.map((r, index) => {
  const [
    slug,
    name,
    city,
    category,
    address,
    phone,
    website,
    terrace,
    brunch,
    champagne,
  ] = r;
  return {
    slug,
    name,
    city,
    category: category as RestaurantCategory,
    address,
    phone,
    website,
    sourceUrl: website.includes("epernay-tourisme.com")
      ? website
      : source(slug),
    drive: minutes[city] ?? "25 min",
    presentation: `${name} est une adresse ${category.toLowerCase()} située à ${city}, sélectionnée pour compléter un séjour romantique chez Absolu. Cette fiche éditoriale rassemble les repères utiles avant de réserver une table et de prendre la route depuis Avize.`,
    why: `Une option à considérer pour ${category === "Gastronomique" ? "une soirée construite autour d’un menu d’auteur" : category === "Champagne" ? "prolonger la découverte du terroir champenois" : category === "Cuisine italienne" ? "changer de registre avec une cuisine italienne conviviale" : "partager un repas à deux dans un cadre adapté à votre programme"}.`,
    advice: `Réservez directement auprès de l’établissement, signalez vos contraintes alimentaires et vérifiez les horaires le jour même. Le trajet indiqué est une estimation depuis Absolu, hors circulation et stationnement.`,
    tags: [
      category,
      city,
      index % 2 ? "Après le séjour" : "Avant votre soirée",
    ],
    terrace,
    brunch,
    champagne,
  };
});
export const getRestaurant = (slug: string) =>
  restaurants.find((item) => item.slug === slug);
