"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireAdmin } from "@/lib/admin/auth";
import { auditAdminAction } from "@/lib/admin/audit";
import { createAdminClient } from "@/lib/supabase/admin";
import { acceptManualReservationRequest, rejectManualReservationRequest } from "@/lib/booking/manual-request-service";

export type RequestActionState={ok:boolean;message:string};
const idFrom=(formData:FormData)=>z.uuid().parse(formData.get("id"));
type ExternalError={message?:unknown;name?:unknown;cause?:unknown;code?:unknown;details?:unknown;hint?:unknown;status?:unknown;statusCode?:unknown};
const safeText=(value:unknown)=>typeof value==="string"?value.slice(0,1000):value==null?null:String(value).slice(0,1000);
const actionErrorMessage=(error:unknown)=>{const outer=(error&&typeof error==="object"?error:{}) as ExternalError,cause=(outer.cause&&typeof outer.cause==="object"?outer.cause:{}) as ExternalError,code=error instanceof Error?error.message:"UNKNOWN";console.error("admin_reservation_request_action_failed",{message:safeText(outer.message),name:safeText(outer.name),cause:safeText(cause.message??outer.cause),supabaseCode:safeText(cause.code??outer.code),details:safeText(cause.details??outer.details),hint:safeText(cause.hint??outer.hint),stripeStatus:safeText(cause.statusCode??cause.status??outer.statusCode??outer.status)});if(code.startsWith("DATES_UNAVAILABLE|")){const[,source,start,end]=code.split("|");return `Impossible de confirmer : ces dates sont déjà bloquées par ${source} (${start} au ${end}).`}const messages:Record<string,string>={RESERVATION_CREATE_FAILED:"Impossible de confirmer : la réservation n’a pas pu être enregistrée.",RESERVATION_REQUEST_INVALID_STATUS:"Impossible de confirmer : cette demande a déjà été traitée.",RESERVATION_REQUEST_ALREADY_PROCESSED:"Impossible de confirmer : cette demande vient déjà d’être traitée.",RESERVATION_REQUEST_PRICE_INVALID:"Impossible de confirmer : le tarif enregistré n’est plus valide.",RESERVATION_REQUEST_NOT_FOUND:"Impossible de confirmer : demande introuvable.",AVAILABILITY_READ_FAILED:"Impossible de confirmer : la disponibilité n’a pas pu être vérifiée."};return messages[code]??"Impossible de confirmer la réservation. Réessayez ou consultez les logs serveur."};
export async function acceptRequest(_state:RequestActionState,formData:FormData):Promise<RequestActionState>{await requireAdmin();try{const id=idFrom(formData);await acceptManualReservationRequest(id);await auditAdminAction("reservation_request.accept","reservation_request",id);revalidatePath("/admin/demandes-reservation");revalidatePath("/admin/calendrier");return{ok:true,message:"Réservation acceptée. Le lien de paiement est prêt."}}catch(error){return{ok:false,message:actionErrorMessage(error)}}}
export async function rejectRequest(_state:RequestActionState,formData:FormData):Promise<RequestActionState>{await requireAdmin();try{const id=idFrom(formData),notes=z.string().trim().max(5000).optional().parse(formData.get("admin_notes")||undefined);await rejectManualReservationRequest(id,notes);await auditAdminAction("reservation_request.reject","reservation_request",id);revalidatePath("/admin/demandes-reservation");revalidatePath("/admin/calendrier");return{ok:true,message:"Demande refusée."}}catch(error){console.error("admin_reservation_request_reject_failed",{code:error instanceof Error?error.message:"UNKNOWN"});return{ok:false,message:"Impossible de refuser la demande."}}}
export async function updateRequest(formData:FormData){await requireAdmin();const input=z.object({id:z.uuid(),nom:z.string().trim().min(1).max(100),prenom:z.string().trim().min(1).max(100),email:z.email(),telephone:z.string().trim().min(6).max(30),message:z.string().trim().max(1500).optional(),admin_notes:z.string().trim().max(5000).optional()}).parse(Object.fromEntries(formData));const{error}=await createAdminClient().from("reservation_requests").update({nom:input.nom,prenom:input.prenom,email:input.email,telephone:input.telephone,message:input.message||null,admin_notes:input.admin_notes||null,updated_at:new Date().toISOString()}).eq("id",input.id).in("statut",["new","accepted"]);if(error)throw new Error("RESERVATION_REQUEST_UPDATE_FAILED");await auditAdminAction("reservation_request.update","reservation_request",input.id);revalidatePath(`/admin/demandes-reservation/${input.id}`);revalidatePath("/admin/demandes-reservation")}
