import Link from "next/link";
import { requireAdmin } from "@/lib/admin/auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { acceptRequest, rejectRequest } from "./actions";

const labels:Record<string,string>={new:"Nouvelle demande",accepted:"Acceptée",pending_payment:"Paiement en attente",confirmed:"Confirmée",rejected:"Refusée",expired:"Expirée",cancelled:"Annulée"};
const tones:Record<string,string>={new:"bg-blue-400/10 text-blue-200",accepted:"bg-emerald-400/10 text-emerald-200",pending_payment:"bg-orange-400/10 text-orange-200",confirmed:"bg-green-400/10 text-green-200",rejected:"bg-rose-400/10 text-rose-200",expired:"bg-zinc-400/10 text-zinc-300",cancelled:"bg-zinc-400/10 text-zinc-300"};
export default async function ReservationRequests(){await requireAdmin();const{data}=await createAdminClient().from("reservation_requests").select("id,created_at,nom,prenom,date_arrivee,date_depart,options,prix_calcule,statut").order("created_at",{ascending:false});return <><AdminPageHeader eyebrow="PMS · Validation manuelle" title="Demandes de réservation" description="Validez personnellement chaque séjour avant d’ouvrir le paiement sécurisé."/><div className="overflow-x-auto rounded-2xl border border-white/10 bg-[#121212] shadow-2xl"><table className="w-full min-w-[1100px] text-left text-xs"><thead className="bg-white/[.04] text-white/40"><tr>{["Nom","Dates","Montant","Options","Créée le","Statut","Actions"].map((label,index)=><th key={`${label}-${index}`} className="p-4">{label}</th>)}</tr></thead><tbody>{data?.map(row=>{const stored=row.options as {pricing?:{extras?:Array<{label:string}>}};return <tr key={row.id} className="border-t border-white/[.07] hover:bg-white/[.025]"><td className="p-4 font-medium">{row.prenom} {row.nom}</td><td>{row.date_arrivee} → {row.date_depart}</td><td>{(row.prix_calcule/100).toLocaleString("fr-FR",{style:"currency",currency:"EUR"})}</td><td className="max-w-56 truncate">{stored.pricing?.extras?.map(item=>item.label).join(", ")||"Aucune"}</td><td>{new Date(row.created_at).toLocaleString("fr-FR")}</td><td><span className={`rounded-full px-3 py-1 ${tones[row.statut]??tones.cancelled}`}>{labels[row.statut]??row.statut}</span></td><td><div className="flex gap-2"><Link href={`/admin/demandes-reservation/${row.id}`} className="rounded-lg border border-white/10 px-3 py-2">Voir</Link>{row.statut==="new"&&<><form action={acceptRequest}><input type="hidden" name="id" value={row.id}/><button className="rounded-lg bg-[#C9A86A] px-3 py-2 text-black">Accepter</button></form><form action={rejectRequest}><input type="hidden" name="id" value={row.id}/><button className="rounded-lg border border-rose-400/30 px-3 py-2 text-rose-200">Refuser</button></form></>}<Link href={`/admin/demandes-reservation/${row.id}#modifier`} className="rounded-lg border border-white/10 px-3 py-2">Modifier</Link></div></td></tr>})}</tbody></table>{!data?.length&&<p className="p-8 text-center text-white/40">Aucune demande de réservation.</p>}</div></>}
