import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, Clock3 } from "lucide-react";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
export const metadata: Metadata = { title: "Journal | Absolu", description: "Inspirations romantiques, bien-être et conseils pour préparer une escapade à deux.", alternates: { canonical: "/blog" } };
const articles = [{ title: "Composer un week-end romantique inoubliable", category: "Inspiration", image: "/images/optimized/lit.webp", excerpt: "Des attentions discrètes aux instants suspendus, imaginez une escapade qui vous ressemble." }, { title: "Baignoire balnéo privative : les bienfaits d’une pause à deux", category: "Bien-être", image: "/images/optimized/salledebain.webp", excerpt: "Chaleur, détente et reconnexion : pourquoi le spa privatif transforme un séjour." }, { title: "Sauna infrarouge, le rituel douceur", category: "Expérience", image: "/images/optimized/sauna.webp", excerpt: "Découvrez une chaleur enveloppante dans l’intimité de votre suite." }];
export default function Blog() { return <><Header /><main><section className="px-5 pb-20 pt-36 text-center"><p className="eyebrow text-[#C9A86A]">Le journal Absolu</p><h1 className="mt-5 font-heading text-5xl sm:text-7xl">L’inspiration à deux</h1><p className="mx-auto mt-5 max-w-xl text-sm leading-7 text-white/50">Conseils, rituels et idées pour transformer une parenthèse en souvenir.</p></section><section className="page-shell grid gap-5 pb-28 lg:grid-cols-3">{articles.map((article) => <article key={article.title} className="group overflow-hidden rounded-[2rem] border border-white/10 bg-[#121212]"><div className="relative aspect-[4/3] overflow-hidden"><Image src={article.image} alt="" fill sizes="(max-width: 1024px) 100vw, 33vw" className="object-cover transition duration-700 group-hover:scale-105" /></div><div className="p-6"><div className="flex items-center justify-between text-[10px] uppercase tracking-wider text-[#C9A86A]"><span>{article.category}</span><span className="flex items-center gap-1 text-white/30"><Clock3 className="size-3" />4 min</span></div><h2 className="mt-4 font-heading text-2xl leading-tight">{article.title}</h2><p className="mt-3 text-sm leading-6 text-white/45">{article.excerpt}</p><Link href="/contact" className="mt-6 inline-flex items-center gap-2 text-xs text-[#D8C8B6]">Préparer mon séjour <ArrowUpRight className="size-3.5" /></Link></div></article>)}</section></main><Footer /></>; }
