import Link from "next/link";
import { CalendarClock, Gift, History, QrCode, ReceiptText, ScanLine, WalletCards } from "lucide-react";
import { requireAdmin } from "@/lib/admin/auth";
import { AdminPageHeader } from "@/components/admin/admin-page-header";

const stages = [{ label: "Création", icon: Gift }, { label: "Paiement Stripe", icon: WalletCards }, { label: "QR sécurisé", icon: QrCode }, { label: "Utilisation", icon: ScanLine }, { label: "Facture", icon: ReceiptText }];
export default async function GiftCards() { await requireAdmin(); return <><AdminPageHeader eyebrow="Bons cadeaux" title="Expériences à offrir" description="Le parcours cadeau est préparé de la création jusqu’à l’utilisation, sans altérer le tunnel de réservation existant." actions={<Link href="/bons-cadeaux" className="rounded-full border border-white/15 px-5 py-3 text-sm">Voir la boutique</Link>} />
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{stages.map((stage, index) => <article key={stage.label} className="rounded-[1.4rem] border border-white/[.08] bg-[#121212] p-5"><stage.icon className="size-5 text-[#C9A86A]" /><p className="mt-5 text-[10px] text-white/30">0{index + 1}</p><h2 className="mt-1 text-sm">{stage.label}</h2></article>)}</section>
  <div className="mt-6 grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><section className="rounded-[1.5rem] border border-white/[.08] bg-[#121212] p-6"><h2 className="font-heading text-2xl">Créer un bon cadeau</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-white/45">Le modèle métier, la validité et l’interface QR sont prêts. L’émission restera volontairement désactivée jusqu’au branchement d’un stockage persistant dédié, afin de garantir une utilisation atomique et antifraude.</p><div className="mt-6 grid gap-3 sm:grid-cols-3">{[150, 250, 350].map((price) => <button key={price} type="button" disabled className="rounded-2xl border border-[#C9A86A]/20 p-5 text-left opacity-60"><span className="font-heading text-3xl text-[#E5C98E]">{price} €</span><span className="mt-2 block text-[10px] text-white/35">Valable 12 mois</span></button>)}</div></section><section className="rounded-[1.5rem] border border-white/[.08] bg-[#121212] p-6"><h2 className="flex items-center gap-2 font-heading text-2xl"><History className="size-4 text-[#C9A86A]" />Historique</h2><div className="mt-8 text-center text-white/30"><CalendarClock className="mx-auto size-8" /><p className="mt-3 text-sm">Aucun bon émis.</p></div></section></div>
  </>; }
