import Link from "next/link";
import { MessageCircleQuestion } from "lucide-react";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { Breadcrumb } from "@/components/shared/breadcrumb";
import { JsonLd } from "@/components/seo/json-ld";
import { conversationalAnswers } from "@/lib/ai-seo/conversations";
import { pageMetadata } from "@/lib/seo";
import { siteConfig } from "@/lib/site-config";
export const metadata=pageMetadata({title:"Réponses sur les Love Rooms en Champagne | Absolu",description:"Réponses directes aux questions naturelles sur les Love Rooms, les week-ends romantiques, Avize et Épernay.",path:"/reponses"});
export default function Answers(){return <><Header/><main className="page-shell pb-24 pt-36"><JsonLd data={{"@context":"https://schema.org","@type":"ItemList",name:"Réponses conversationnelles Absolu",itemListElement:conversationalAnswers.map((item,index)=>({"@type":"ListItem",position:index+1,name:item.question,url:`${siteConfig.url}/reponses/${item.slug}`}))}}/><Breadcrumb current="Réponses"/><p className="eyebrow mt-12 text-[#C9A86A]">Questions naturelles</p><h1 className="mt-4 max-w-5xl font-heading text-6xl sm:text-8xl">Une réponse claire, avant de choisir.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-white/60">Des faits concis, des explications détaillées et des liens vers les pages qui permettent de vérifier chaque information.</p><section className="mt-16 grid gap-5 md:grid-cols-2">{conversationalAnswers.map(item=><article key={item.slug} className="rounded-[2rem] border border-white/10 bg-[#121212] p-7"><MessageCircleQuestion className="size-6 text-[#C9A86A]"/><h2 className="mt-5 font-heading text-4xl"><Link href={`/reponses/${item.slug}`}>{item.question}</Link></h2><p className="mt-4 leading-7 text-white/50">{item.shortAnswer}</p><Link href={`/reponses/${item.slug}`} className="mt-6 inline-block text-sm text-[#C9A86A]">Lire la réponse complète →</Link></article>)}</section><nav aria-label="Ressources complémentaires" className="mt-20 flex flex-wrap gap-4"><Link href="/ressources" className="rounded-full border border-white/15 px-5 py-3">Guides piliers</Link><Link href="/glossaire" className="rounded-full border border-white/15 px-5 py-3">Glossaire</Link><Link href="/faq" className="rounded-full border border-white/15 px-5 py-3">FAQ complète</Link></nav></main><Footer/></>}
