import Image from "next/image";
import { ArrowUpRight } from "lucide-react";
import { experiences } from "@/lib/constants";
import { Reveal } from "@/components/shared/reveal";
import { SectionHeading } from "@/components/shared/section-heading";

export function ExperienceGrid() {
  return <section id="experiences" className="bg-[#0D0D0D] py-24 sm:py-32"><div className="page-shell"><Reveal><SectionHeading light eyebrow="Expériences privées" title="Tout ce qu’il faut pour oublier le reste." description="Trois espaces, une même intention : offrir à votre couple un rituel de détente et le luxe rare de ne penser à rien." /></Reveal><div className="mt-14 grid gap-5 lg:grid-cols-3">{experiences.map((item, i) => <Reveal key={item.title} delay={i * .08}><article className="group relative min-h-[34rem] overflow-hidden bg-[#151515] focus-within:ring-1 focus-within:ring-[#C9A86A]"><Image src={item.natural} alt={`${item.title} de la suite Absolu`} fill sizes="(min-width: 1024px) 33vw, 100vw" className={`object-cover transition-opacity duration-700 ${item.position}`} /><Image src={item.ambient} alt="" aria-hidden="true" fill sizes="(min-width: 1024px) 33vw, 100vw" className={`hidden object-cover opacity-0 transition-opacity duration-700 group-hover:opacity-100 group-focus-within:opacity-100 md:block ${item.position}`} /><div className="absolute inset-0 bg-gradient-to-t from-black via-black/20 to-transparent" /><div className="absolute inset-x-0 bottom-0 p-7"><p className="mb-3 text-[.65rem] uppercase tracking-[.2em] text-[#D8C8B6]">{item.detail}</p><h3 className="font-heading text-3xl">{item.title}</h3><p className="mt-3 text-sm leading-6 text-white/65">{item.description}</p><a href="#galerie" className="mt-5 inline-flex items-center gap-2 text-xs uppercase tracking-[.16em] text-[#C9A86A]">Découvrir <ArrowUpRight className="size-4" aria-hidden="true" /></a></div></article></Reveal>)}</div></div></section>;
}
