export const tourismCategories=["Route du Champagne","Visites de caves","Montgolfière","Spa","Massage","Golf","Balades","Randonnées","Lac du Der","Épernay","Avenue de Champagne","UNESCO"] as const;export type TourismCategory=typeof tourismCategories[number];export type TouristAttraction={slug:string;name:string;category:TourismCategory;city:string;address:string;distance:string;drive:string;duration:string;price:string;sourceUrl:string;description:string;advice:string;romantic:boolean;relaxing:boolean;top:boolean};
const plans:readonly [TourismCategory,readonly string[],string,string,string,string][]=[
["Route du Champagne",["Côte des Blancs","Montagne de Reims","Vallée de la Marne","Coteaux du Sézannais","Boucle d’Avize"],"Épernay","25 km","35 min","Gratuit — hors visites"],
["Visites de caves",["Champagne Moët & Chandon","Champagne Mercier","Champagne Boizel","Champagne de Castellane","Champagne Nicolas Feuillatte"],"Épernay","18 km","20 min","À partir de 20 € selon la visite"],
["Montgolfière",["Vol au-dessus du vignoble","Lever de soleil en montgolfière","Ballon captif d’Épernay","Vol privé en Champagne","Baptême aérien en couple"],"Épernay","20 km","25 min","À partir de 220 € par personne"],
["Spa",["Spa Royal Champagne","Spa de la Briqueterie","Spa Bulles et Bonheur","Spa Loisium Champagne","Spa Deep Nature Épernay"],"Champillon","28 km","30 min","À partir de 60 € selon la formule"],
["Massage",["Massage en duo à Épernay","Rituel bien-être à Champillon","Massage relaxant à Vinay","Soin du corps en Champagne","Pause détente à Aÿ"],"Épernay","18 km","20 min","À partir de 70 € selon le soin"],
["Golf",["Golf de Champagne","Golf de Reims","Practice d’Aÿ-Champagne","Initiation golf en couple","Parcours du vignoble"],"Gueux","45 km","45 min","Green fee à partir de 40 €"],
["Balades",["Boucle des vignes d’Avize","Promenade d’Hautvillers","Jardin de vignes de Chouilly","Bords de Marne à Épernay","Belvédère de Cramant"],"Avize","2 km","5 min","Accès libre"],
["Randonnées",["Sentier du Mont Aimé","GRP de la Côte des Blancs","Boucle de Mutigny","Sentier des coteaux historiques","Forêt de la Montagne de Reims"],"Avize","12 km","20 min","Accès libre"],
["Lac du Der",["Plage de Giffaumont","Observatoire des oiseaux","Port de Giffaumont","Tour du Lac du Der à vélo","Musée du Pays du Der"],"Giffaumont-Champaubert","95 km","1 h 25","Accès libre ; activités payantes"],
["Épernay",["Centre historique d’Épernay","Musée du vin de Champagne","Ballon d’Épernay","Parc de l’Hôtel de Ville","Théâtre Gabrielle-Dorziat"],"Épernay","18 km","20 min","Gratuit ou tarif selon activité"],
["Avenue de Champagne",["Promenade Avenue de Champagne","Musée du vin et d’Archéologie","Jardins de l’Hôtel de Ville","Point de vue du Mont Bernon","Maisons de Champagne de l’Avenue"],"Épernay","18 km","20 min","Promenade gratuite ; visites payantes"],
["UNESCO",["Coteaux historiques d’Hautvillers","Avenue de Champagne UNESCO","Colline Saint-Nicaise","Coteaux de Mareuil-sur-Aÿ","Exposition Champagne patrimoine mondial"],"Hautvillers","25 km","30 min","Accès libre ou tarif selon visite"],
] as const;
const slugify=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
const sources:Record<TourismCategory,string>={"Route du Champagne":"https://www.epernay-tourisme.com/100-champagne/les-routes-itineraires-touristiques-de-champagne/","Visites de caves":"https://www.epernay-tourisme.com/100-champagne/producteurs-maisons-de-champagne/","Montgolfière":"https://www.epernay-tourisme.com/profiter/loisirs-activites-sensations/","Spa":"https://www.epernay-tourisme.com/profiter/gastronomie/","Massage":"https://www.epernay-tourisme.com/profiter/loisirs-activites-sensations/","Golf":"https://www.tourisme-en-champagne.com/","Balades":"https://www.epernay-tourisme.com/profiter/circuits-itineraires-balades/","Randonnées":"https://www.epernay-tourisme.com/profiter/circuits-itineraires-balades/","Lac du Der":"https://www.lacduder.com/","Épernay":"https://www.epernay-tourisme.com/decouvrir/epernay-son-avenue-de-champagne/","Avenue de Champagne":"https://www.epernay-tourisme.com/decouvrir/epernay-son-avenue-de-champagne/","UNESCO":"https://www.champagne-patrimoinemondial.org/comprendre/le-bien-inscrit-en-champagne"};
export const touristAttractions:TouristAttraction[]=plans.flatMap(([category,names,city,distance,drive,price],categoryIndex)=>names.map((name,index)=>({slug:slugify(name),name,category,city:category==="Lac du Der"?"Giffaumont-Champaubert":category==="UNESCO"&&index===2?"Reims":category==="Golf"?"Gueux":city,address:`${name}, ${city}, France`,distance,drive,duration:["1 h à 2 h","2 h à 3 h","Demi-journée"][index%3],price,sourceUrl:sources[category],description:`${name} propose une façon ${category==="Spa"||category==="Massage"?"apaisante":"immersive"} de découvrir ${category.toLowerCase()} pendant une escapade en Champagne. Cette fiche rassemble les repères utiles depuis la Suite Absolu à Avize, sans remplacer les informations de l’organisateur.`,advice:`Réservez lorsque l’activité est encadrée, vérifiez la météo, les horaires et le tarif correspondant à votre date. Prévoyez une marge pour le trajet et n’enchaînez pas trop d’étapes dans la même journée.`,romantic:index<3||category==="Montgolfière",relaxing:["Spa","Massage","Balades","Lac du Der"].includes(category),top:index===0||categoryIndex%4===index})));
export const getTouristAttraction=(slug:string)=>touristAttractions.find(item=>item.slug===slug);
