import 'server-only';import {getStaySettings} from '@/lib/stay-settings';import {createHash} from 'node:crypto';import {render} from '@react-email/components';import {Resend} from 'resend';import {createAdminClient} from '@/lib/supabase/admin';import {ReservationConfirmationEmail} from '@/emails/templates/reservation-confirmation';import {ReservationAdminEmail} from '@/emails/templates/reservation-admin';import {PaymentFailedEmail} from '@/emails/templates/payment-failed';import {CancelledEmail} from '@/emails/templates/cancelled';import {RefundedEmail} from '@/emails/templates/refunded';import {ContactMessageEmail} from '@/emails/templates/contact-message';
import {ReservationRequestStatusEmail,type ReservationRequestEmailKind} from '@/emails/templates/reservation-request-status';
export type BookingEmailData={reference:string;firstName:string;email:string;checkIn:string;checkOut:string;totalAmount:number};const recipientHash=(to:string)=>createHash('sha256').update(to.trim().toLowerCase()).digest('hex');
async function logEmail(template:string,to:string,status:'sent'|'failed'|'skipped',providerId?:string,errorCode?:string){try{await createAdminClient().from('email_logs').insert({template,recipient_hash:recipientHash(to),status,provider_id:providerId??null,error_code:errorCode??null})}catch{console.error('email_log_failed',{template,status})}}
async function send(to:string,subject:string,template:string,component:React.ReactElement){const key=process.env.RESEND_API_KEY,from=process.env.RESEND_FROM,replyTo=process.env.RESEND_REPLY_TO;if(!key||!from){if(process.env.NODE_ENV!=='production')console.info('email_skipped_dev',{template});return}try{const html=await render(component),result=await new Resend(key).emails.send({from,to,subject,html,...(replyTo?{replyTo}:{})});if(result.error)throw new Error(result.error.name);await logEmail(template,to,'sent',result.data?.id)}catch(error){await logEmail(template,to,'failed',undefined,error instanceof Error?error.message.slice(0,80):'UNKNOWN');throw new Error('EMAIL_SEND_FAILED')}}
export async function sendConfirmation(data:BookingEmailData){const admin=process.env.ADMIN_EMAIL,staySettings=await getStaySettings();await Promise.all([send(data.email,`Votre réservation  est confirmée`,'reservation-confirmation',<ReservationConfirmationEmail {...data} staySettings={staySettings}/>),admin?send(admin,`Nouvelle réservation `,'reservation-admin',<ReservationAdminEmail {...data} staySettings={staySettings}/>):Promise.resolve()])}
export async function sendStatusEmail(kind:'failed'|'cancelled'|'refunded',data:BookingEmailData){const templates={failed:<PaymentFailedEmail {...data}/>,cancelled:<CancelledEmail {...data}/>,refunded:<RefundedEmail {...data}/>},subjects={failed:'Votre paiement nâ€™a pas abouti',cancelled:'Votre rÃ©servation a Ã©tÃ© annulÃ©e',refunded:'Votre remboursement a Ã©tÃ© traitÃ©'};await send(data.email,subjects[kind],kind,templates[kind])}
export async function sendContactMessage(message:{name:string;email:string;phone?:string;message:string}){const admin=process.env.ADMIN_EMAIL;if(!admin)throw new Error('ADMIN_EMAIL_NOT_CONFIGURED');await send(admin,'Nouveau message depuis le site Absolu','contact',<ContactMessageEmail {...message}/>)}
export async function sendReservationRequestEmail(kind:ReservationRequestEmailKind,data:{firstName:string;email:string;checkIn:string;checkOut:string;totalAmount:number;checkoutUrl?:string}){const subjects:Record<ReservationRequestEmailKind,string>={received:'Votre demande de réservation a bien été reçue',accepted:'Votre demande a été acceptée',payment_pending:'Votre paiement est en attente',rejected:'Réponse à votre demande de réservation',expired:'Votre demande de réservation a expiré'};await send(data.email,subjects[kind],`reservation-request-${kind}`,<ReservationRequestStatusEmail kind={kind}{...data}/>)}

