import { Bath, BedDouble, Coffee, DoorOpen, House, Maximize, Radio, ShowerHead, Thermometer, Tv, Utensils, Wind, Wifi } from "lucide-react";
import { pageMetadata } from "@/lib/seo";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { InteriorHero } from "@/components/shared/interior-hero";
import { WellnessAtmosphere } from "@/components/amenities/wellness-atmosphere";
import { TantraExperience } from "@/components/amenities/tantra-experience";

export const metadata = pageMetadata({ title: "Équipements & rituels de bien-être | Absolu", description: "Découvrez les équipements premium et l’atmosphère propice à la reconnexion du couple dans la Suite Absolu à Avize.", path: "/equipements" });
const groups = [{ title: "Bien-être", intro: "Un espace entièrement privé, disponible à votre rythme.", items: [["Baignoire balnéo", Bath], ["Sauna privatif", Radio]] }, { title: "Coin café", intro: "Tout le nécessaire pour préparer un petit-déjeuner ou une collation.", items: [["Réfrigérateur", Utensils], ["Micro-ondes", Utensils], ["Machine à café", Coffee], ["Bouilloire électrique", Coffee], ["Grille-pain", Utensils], ["Coin repas", Utensils]] }, { title: "Confort", intro: "Des équipements choisis pour une parenthèse simple et paisible.", items: [["35 m²", Maximize], ["Grand lit double", BedDouble], ["Coin salon", House], ["Télévision écran plat", Tv], ["Wi-Fi gratuit", Wifi], ["Climatisation", Wind], ["Chauffage", Thermometer], ["Penderie", House], ["Entrée indépendante", DoorOpen], ["Logement indépendant", House], ["Rez-de-chaussée", House]] }, { title: "Salle de bains privative", intro: "Un rituel de bien-être aux lignes sobres et contemporaines.", items: [["Douche à l’italienne", ShowerHead], ["Baignoire balnéo", Bath]] }] as const;

export default function AmenitiesPage() { return <><Header /><main><InteriorHero image="/images/optimized/salledebainviolet.webp" title="Les équipements" eyebrow="Le confort au service du moment" description="Baignoire balnéo, sauna privatif, coin café et confort premium : tout est réuni pour votre séjour à deux." /><section className="bg-[#F5F2EC] py-24 text-[#171411] sm:py-32"><div className="page-shell space-y-20">{groups.map((group) => <section key={group.title} className="grid gap-8 lg:grid-cols-[.36fr_1fr] lg:gap-16"><div><div className="flex items-center gap-4"><span className="gold-line" /><h2 className="font-heading text-4xl sm:text-5xl">{group.title}</h2></div><p className="mt-5 max-w-sm text-sm leading-7 text-[#665E56]">{group.intro}</p></div><div className="grid grid-cols-2 border-l border-t border-black/10 sm:grid-cols-3">{group.items.map(([label, Icon]) => <div key={label} className="min-h-32 border-b border-r border-black/10 p-5 transition-colors hover:bg-white/45 sm:p-6"><Icon className="size-5 text-[#9A7844]" aria-hidden="true" /><p className="mt-4 text-sm leading-6">{label}</p></div>)}</div></section>)}</div></section><WellnessAtmosphere/><TantraExperience/></main><Footer /></>; }
