import { Bath, BedDouble, Coffee, DoorOpen, Flower2, Gamepad2, House, Maximize, Radio, ShowerHead, Sparkles, Thermometer, Tv, Utensils, Wind, Wifi } from "lucide-react";
import { pageMetadata } from "@/lib/seo";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { InteriorHero } from "@/components/shared/interior-hero";
import { TantraExperience } from "@/components/amenities/tantra-experience";

export const metadata = pageMetadata({ title: "Équipements | Suite Absolu", description: "Découvrez les équipements de bien-être, de cuisine, de confort et de salle de bain de la Suite Absolu.", path: "/equipements" });
const groups = [{ title: "Bien-être", intro: "Un espace entièrement privé, disponible à votre rythme.", items: [["Baignoire balnéo", Bath], ["Sauna privatif", Radio], ["Ambiance lumineuse", Sparkles], ["Expérience Tantra", Flower2], ["Suite 100 % privative", House]] }, { title: "Coin café & gourmandises", intro: "Tout le nécessaire pour préparer un petit-déjeuner ou une collation.", items: [["Réfrigérateur", Utensils], ["Micro-ondes", Utensils], ["Machine à café", Coffee], ["Bouilloire électrique", Coffee], ["Grille-pain", Utensils], ["Coin repas", Utensils]] }, { title: "Confort", intro: "Des équipements choisis pour une parenthèse simple et paisible.", items: [["Suite de 35 m²", Maximize], ["Grand lit double", BedDouble], ["Coin salon", House], ["Télévision connectée & Netflix", Tv], ["Wi-Fi gratuit", Wifi], ["Climatisation", Wind], ["Chauffage", Thermometer], ["Réveil", Coffee], ["Armoire & penderie", House], ["Jeux de société", Gamepad2], ["Entrée indépendante", DoorOpen], ["Rez-de-chaussée", House], ["Espace non-fumeur", Sparkles]] }, { title: "Salle de bains privative", intro: "Un rituel de bien-être aux lignes sobres et contemporaines.", items: [["Douche à l’italienne", ShowerHead], ["Baignoire balnéo", Bath], ["Peignoirs", Sparkles], ["Serviettes", Sparkles], ["Sèche-cheveux", Wind], ["Articles de toilette offerts", Bath], ["Papier toilette", Sparkles]] }] as const;

export default function AmenitiesPage() { return <><Header /><main><InteriorHero image="/images/optimized/salledebainviolet.webp" title="Les équipements" eyebrow="Le confort au service du moment" description="Spa privatif, kitchenette et attentions essentielles : tout est réuni pour profiter pleinement de votre séjour à deux." /><section className="bg-[#F5F2EC] py-24 text-[#171411] sm:py-32"><div className="page-shell space-y-20">{groups.map((group) => <section key={group.title} className="grid gap-8 lg:grid-cols-[.36fr_1fr] lg:gap-16"><div><div className="flex items-center gap-4"><span className="gold-line" /><h2 className="font-heading text-4xl sm:text-5xl">{group.title}</h2></div><p className="mt-5 max-w-sm text-sm leading-7 text-[#665E56]">{group.intro}</p></div><div className="grid grid-cols-2 border-l border-t border-black/10 sm:grid-cols-3">{group.items.map(([label, Icon]) => <div key={label} className="min-h-32 border-b border-r border-black/10 p-5 transition-colors hover:bg-white/45 sm:p-6"><Icon className="size-5 text-[#9A7844]" aria-hidden="true" /><p className="mt-4 text-sm leading-6">{label}</p></div>)}</div></section>)}</div></section><TantraExperience /></main><Footer /></>; }
