import type { Metadata } from "next";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { LegalLayout } from "@/components/shared/legal-layout";
import { legalConfig as legal } from "@/lib/site-config";

export const metadata:Metadata={title:"Politique relative aux cookies | Love Room Absolu",description:"Informations sur les cookies et la gestion du consentement sur le site Love Room Absolu.",robots:{index:false,follow:true},alternates:{canonical:"/cookies"}};

export default function CookiesPolicy(){return <><Header/><LegalLayout title="Politique relative aux cookies"><section><h2>1. Qu’est-ce qu’un cookie ?</h2><p>Un cookie ou traceur est un petit fichier ou identifiant utilisé par un site pour assurer son fonctionnement, mémoriser un choix ou mesurer une audience. Certains sont strictement nécessaires ; d’autres requièrent votre consentement.</p></section><section><h2>2. Traceurs nécessaires</h2><p>Ces traceurs permettent la sécurité, la navigation, la gestion de session, la réservation et la conservation de vos choix de confidentialité. Ils ne peuvent pas être désactivés depuis le bandeau lorsqu’ils sont indispensables au service demandé.</p></section><section><h2>3. Mesure d’audience</h2><p>Si vous l’acceptez, des outils de mesure d’audience peuvent nous aider à comprendre l’utilisation du site et à améliorer ses contenus. Ils restent désactivés avant votre accord lorsque celui-ci est requis.</p></section><section><h2>4. Préférences et marketing</h2><p>Les traceurs de préférences peuvent mémoriser certains choix d’affichage. Les traceurs marketing peuvent mesurer une campagne ou personnaliser un contenu publicitaire. Ces deux catégories sont facultatives et désactivées par défaut.</p></section><section><h2>5. Votre choix</h2><p>Lors de votre première visite, le bandeau permet de tout accepter, tout refuser ou choisir par finalité. Refuser est aussi simple qu’accepter. Vous pouvez rouvrir le panneau à tout moment grâce au bouton « Cookies » affiché en bas du site. Le retrait du consentement n’affecte pas la licéité des opérations antérieures.</p></section><section><h2>6. Durée</h2><p>La durée de vie des traceurs est limitée à ce qui est nécessaire à leur finalité. Votre choix est conservé pendant une durée raisonnable, puis le bandeau peut vous solliciter de nouveau. Vous pouvez également supprimer les cookies depuis les réglages de votre navigateur.</p></section><section><h2>7. Services tiers</h2><p>Selon les fonctionnalités effectivement activées et votre consentement, le site peut charger des services de mesure d’audience ou de marketing tiers. Leurs politiques s’appliquent aux traitements qu’ils réalisent en qualité de responsables distincts ou de sous-traitants.</p></section><section><h2>8. Contact</h2><p>Pour toute question : <a href={`mailto:${legal.email}`}>{legal.email}</a>. Pour en savoir plus sur vos données, consultez la <a href="/confidentialite">politique de confidentialité</a>.</p></section></LegalLayout><Footer/></>}
