import type { Metadata } from "next";
import Image from "next/image";
import { notFound } from "next/navigation";
import { CalendarDays, Clock3, ExternalLink, KeyRound, Mail, Phone, Users, Wifi } from "lucide-react";
import { getGuestPortal } from "@/lib/guest-portal/repository";
import { CopyButton } from "@/components/guest-portal/copy-button";
import { completePrecheckin } from "./actions";
export const dynamic="force-dynamic";
export const metadata:Metadata={title:"Mon séjour | Absolu",robots:{index:false,follow:false}};
const date=(v:string)=>new Intl.DateTimeFormat("fr-FR",{day:"numeric",month:"long",year:"numeric",timeZone:"Europe/Paris"}).format(new Date(`${v}T12:00:00Z`));
const euro=(v:number)=>new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format(v/100);
const card="rounded-[1.7rem] border border-[#c9a86a]/20 bg-[#15110f]/90 p-5 shadow-2xl sm:p-7";
export default async function GuestPortalPage({params}:{params:Promise<{token:string}>}){const{token}=await params,data=await getGuestPortal(token);if(!data)notFound();const{reservation:r,settings:s,expired,keyboxCode,revealTime}=data;
  const instructions=[['Balnéo',s.balneoInstructions],['Sauna',s.saunaInstructions],['Télévision / streaming',s.tvInstructions],['Kitchenette',s.kitchenInstructions],['Machine à café',s.coffeeInstructions],['Chauffage / climatisation',s.climateInstructions]].filter(([,v])=>v);
  return <main className="min-h-screen bg-[#090807] text-[#f7f1e8]"><div className="mx-auto max-w-3xl px-4 py-8 sm:px-6 sm:py-14"><header className="mb-6 overflow-hidden rounded-[2rem] border border-[#c9a86a]/25 bg-[radial-gradient(circle_at_top_right,rgba(201,168,106,.2),transparent_45%),linear-gradient(145deg,#1b1512,#0c0a09)] p-6 sm:p-10"><p className="text-xs tracking-[.42em] text-[#d9bb80]">ABSOLU</p><h1 className="mt-8 font-heading text-4xl sm:text-6xl">Bonjour {r.guest_first_name}</h1><p className="mt-2 text-lg text-white/55">Votre séjour chez Absolu</p><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-3"><Stat icon={CalendarDays} value={`${date(r.check_in)} → ${date(r.check_out)}`}/><Stat icon={Clock3} value={`${r.nights} nuit${r.nights>1?'s':''}`}/><Stat icon={Users} value={`${r.guest_count} voyageur${r.guest_count>1?'s':''}`}/></div></header>
  {expired?<section className={card}><h2 className="font-heading text-3xl">Ce séjour est terminé.</h2><p className="mt-3 text-white/55">Pour votre sécurité, les informations d’accès et le WiFi ne sont plus affichés.</p></section>:<><section className={card}><p className="text-xs tracking-[.25em] text-[#d9bb80]">PRÉPARER MON ARRIVÉE</p><form action={completePrecheckin} className="mt-5 grid gap-4 sm:grid-cols-2"><input type="hidden" name="token" value={token}/><Field name="firstName" label="Prénom" value={r.guest_first_name}/><Field name="lastName" label="Nom" value={r.guest_last_name}/><Field name="phone" label="Téléphone" value={r.guest_phone}/><Field name="guestCount" label="Voyageurs" value={String(r.guest_count)} type="number"/><Field name="estimatedArrivalTime" label="Heure approximative d’arrivée" value={String(r.estimated_arrival_time??'18:00').slice(0,5)} type="time"/><label className="flex gap-3 text-sm text-white/65 sm:col-span-2"><input required type="checkbox" name="rulesAccepted" defaultChecked={Boolean(r.guest_rules_accepted_at)}/><span>J’ai pris connaissance des informations et du règlement du séjour.</span></label><button className="min-h-12 rounded-full bg-[#c9a86a] px-6 font-semibold text-black sm:col-span-2">{r.precheckin_completed_at?'Mettre à jour':'Valider mon pré-check-in'}</button></form></section>
  <Section title="Ma réservation"><Line label="Référence" value={r.reference}/><Line label="Arrivée" value={`${date(r.check_in)}, à partir de ${s.checkInTime.replace(':','h')}`}/><Line label="Départ" value={`${date(r.check_out)}, avant ${s.checkOutTime.replace(':','h')}`}/><Line label="Voyageurs" value={String(r.guest_count)}/><Line label="Montant payé" value={euro(r.total)}/>{r.reservation_options?.map((o:{label:string;quantity:number;total:number})=><Line key={o.label} label={o.quantity>1?`${o.label} × ${o.quantity}`:o.label} value={euro(o.total)}/>)}</Section>
  <Section title="Accès"><p className="whitespace-pre-line text-white/70">{s.address}</p><div className="mt-4 flex flex-wrap gap-3"><a className="inline-flex min-h-11 items-center gap-2 rounded-full bg-[#c9a86a] px-5 text-sm font-semibold text-black" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(s.address)}`}><ExternalLink className="size-4"/>Ouvrir dans Maps</a><CopyButton value={s.address} label="Copier l’adresse"/></div>{s.accessInstructions&&<TextBlock title="Instructions" value={s.accessInstructions}/>} {s.parkingInstructions&&<TextBlock title="Stationnement" value={s.parkingInstructions}/>} {s.entranceImageUrl&&<Image className="mt-5 rounded-2xl object-cover" src={s.entranceImageUrl} alt="Repérage de l’entrée" width={900} height={600}/>}</Section>
  <Section title="Votre accès"><div className="rounded-2xl border border-[#c9a86a]/25 bg-black/30 p-5 text-center"><KeyRound className="mx-auto size-6 text-[#d9bb80]"/>{keyboxCode?<><p className="mt-3 text-xs uppercase tracking-[.25em] text-white/40">Code boîte à clés</p><p className="my-4 font-mono text-4xl tracking-[.35em] text-[#f0d497]">{keyboxCode}</p><CopyButton value={keyboxCode} label="Copier le code"/></>:<><p className="mt-3 text-lg">Votre code d’accès sera disponible le jour de votre arrivée à {revealTime.replace(':','h')}.</p><p className="mt-2 text-sm text-white/45">Le serveur vérifiera automatiquement que votre séjour est éligible.</p></>}</div>{s.keyboxInstructions&&<TextBlock title="Boîte à clés" value={s.keyboxInstructions}/>} {s.keyboxImageUrl&&keyboxCode&&<Image className="mt-5 rounded-2xl object-cover" src={s.keyboxImageUrl} alt="Emplacement de la boîte à clés" width={900} height={600}/>}</Section>
  {(s.wifiName||s.wifiPassword)&&<Section title="WiFi"><Wifi className="mb-3 size-5 text-[#d9bb80]"/><Line label="Réseau" value={s.wifiName}/>{s.wifiPassword&&<div className="mt-4"><CopyButton value={s.wifiPassword} label="Copier le mot de passe"/></div>}</Section>}
  {instructions.length>0&&<Section title="Équipements / mode d’emploi">{instructions.map(([title,value])=><TextBlock key={title} title={title} value={value}/>)}</Section>}
  {(s.houseRules||s.checkoutInstructions)&&<Section title="Règlement / consignes">{s.houseRules&&<TextBlock title="Règlement" value={s.houseRules}/>} {s.checkoutInstructions&&<TextBlock title="Consignes de départ" value={s.checkoutInstructions}/>}</Section>}</>}
  <Section title="Contact"><div className="flex flex-wrap gap-3"><a className="inline-flex min-h-11 items-center gap-2 rounded-full bg-[#c9a86a] px-5 text-sm text-black" href={`tel:${s.phone}`}><Phone className="size-4"/>Appeler</a><a className="inline-flex min-h-11 items-center gap-2 rounded-full border border-white/15 px-5 text-sm" href={`mailto:${s.email}`}><Mail className="size-4"/>E-mail</a></div></Section><footer className="py-8 text-center text-xs tracking-[.25em] text-white/25">ABSOLU · AVIZE</footer></div></main>}
function Stat({icon:Icon,value}:{icon:typeof CalendarDays;value:string}){return <div className="rounded-2xl border border-white/10 bg-white/[.04] p-3 text-sm"><Icon className="mb-2 size-4 text-[#d9bb80]"/>{value}</div>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className={`${card} mt-5`}><h2 className="font-heading text-3xl">{title}</h2><div className="mt-5">{children}</div></section>}
function Line({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-5 border-b border-white/[.07] py-3 text-sm"><span className="text-white/45">{label}</span><span className="text-right">{value}</span></div>}
function TextBlock({title,value}:{title:string;value:string}){return <div className="mt-5"><h3 className="text-sm text-[#d9bb80]">{title}</h3><p className="mt-2 whitespace-pre-line text-sm leading-7 text-white/60">{value}</p></div>}
function Field({name,label,value,type="text"}:{name:string;label:string;value:string;type?:string}){return <label className="text-sm text-white/55"><span className="mb-2 block text-white/75">{label}</span><input required min={type==='number'?1:undefined} max={type==='number'?2:undefined} className="min-h-12 w-full border border-white/10 bg-black/30 px-4 text-white" name={name} type={type} defaultValue={value}/></label>}
