import type { Locale } from "./config";

type UiDictionary = {
  skip: string; chooseLanguage: string; openMenu: string; closeMenu: string;
  nav: { suite: string; gallery: string; explore: string; contact: string; guide: string; restaurants: string; magazine: string; equipment: string; faq: string; gifts: string; book: string };
  footer: { tagline: string; stay: string; contact: string; rights: string; newsletter: string };
  cookies: { button: string; title: string; body: string; learn: string; analytics: string; marketing: string; preferences: string; reject: string; save: string; accept: string };
};

const fr: UiDictionary = {
  skip: "Aller au contenu", chooseLanguage: "Choisir la langue", openMenu: "Ouvrir le menu", closeMenu: "Fermer le menu",
  nav: { suite: "La Suite", gallery: "Galerie", explore: "Explorer", contact: "Contact", guide: "Guide touristique", restaurants: "Restaurants", magazine: "Magazine", equipment: "Équipements", faq: "FAQ", gifts: "Bons cadeaux", book: "Réserver maintenant" },
  footer: { tagline: "Une suite romantique confidentielle, imaginée pour le bien-être et la reconnexion du couple.", stay: "Séjour & Champagne", contact: "Nous contacter", rights: "Tous droits réservés.", newsletter: "Newsletter" },
  cookies: { button: "Cookies", title: "Votre intimité compte.", body: "Les cookies nécessaires fonctionnent toujours. Les autres restent désactivés sans votre accord.", learn: "En savoir plus", analytics: "Mesure d’audience", marketing: "Marketing", preferences: "Préférences", reject: "Tout refuser", save: "Enregistrer", accept: "Tout accepter" },
};

export const uiDictionaries: Record<Locale, UiDictionary> = {
  fr,
  en: { ...fr, skip: "Skip to content", chooseLanguage: "Choose language", openMenu: "Open menu", closeMenu: "Close menu", nav: { suite: "The suite", gallery: "Gallery", explore: "Explore", contact: "Contact", guide: "Travel guide", restaurants: "Restaurants", magazine: "Magazine", equipment: "Facilities", faq: "FAQ", gifts: "Gift vouchers", book: "Book now" }, footer: { tagline: "A private romantic suite designed for wellbeing and time together.", stay: "Stay & Champagne", contact: "Contact us", rights: "All rights reserved.", newsletter: "Newsletter" }, cookies: { button: "Cookies", title: "Your privacy matters.", body: "Necessary cookies always work. All others remain disabled without your consent.", learn: "Learn more", analytics: "Analytics", marketing: "Marketing", preferences: "Preferences", reject: "Reject all", save: "Save", accept: "Accept all" } },
  de: { ...fr, skip: "Zum Inhalt", chooseLanguage: "Sprache wählen", openMenu: "Menü öffnen", closeMenu: "Menü schließen", nav: { suite: "Die Suite", gallery: "Galerie", explore: "Entdecken", contact: "Kontakt", guide: "Reiseführer", restaurants: "Restaurants", magazine: "Magazin", equipment: "Ausstattung", faq: "FAQ", gifts: "Gutscheine", book: "Jetzt buchen" }, footer: { tagline: "Eine private romantische Suite für Wohlbefinden und gemeinsame Zeit.", stay: "Aufenthalt & Champagne", contact: "Kontakt", rights: "Alle Rechte vorbehalten.", newsletter: "Newsletter" }, cookies: { button: "Cookies", title: "Ihre Privatsphäre ist wichtig.", body: "Notwendige Cookies sind immer aktiv. Alle anderen bleiben ohne Ihre Zustimmung deaktiviert.", learn: "Mehr erfahren", analytics: "Reichweitenmessung", marketing: "Marketing", preferences: "Einstellungen", reject: "Alle ablehnen", save: "Speichern", accept: "Alle akzeptieren" } },
  nl: { ...fr, skip: "Naar inhoud", chooseLanguage: "Taal kiezen", openMenu: "Menu openen", closeMenu: "Menu sluiten", nav: { suite: "De suite", gallery: "Galerij", explore: "Ontdekken", contact: "Contact", guide: "Reisgids", restaurants: "Restaurants", magazine: "Magazine", equipment: "Voorzieningen", faq: "FAQ", gifts: "Cadeaubonnen", book: "Nu boeken" }, footer: { tagline: "Een privésuite voor romantiek, welzijn en tijd samen.", stay: "Verblijf & Champagne", contact: "Contact", rights: "Alle rechten voorbehouden.", newsletter: "Nieuwsbrief" }, cookies: { button: "Cookies", title: "Uw privacy telt.", body: "Noodzakelijke cookies werken altijd. Andere blijven zonder toestemming uitgeschakeld.", learn: "Meer informatie", analytics: "Analyse", marketing: "Marketing", preferences: "Voorkeuren", reject: "Alles weigeren", save: "Opslaan", accept: "Alles accepteren" } },
  it: { ...fr, skip: "Vai al contenuto", chooseLanguage: "Scegli la lingua", openMenu: "Apri il menu", closeMenu: "Chiudi il menu", nav: { suite: "La suite", gallery: "Galleria", explore: "Esplora", contact: "Contatti", guide: "Guida di viaggio", restaurants: "Ristoranti", magazine: "Magazine", equipment: "Dotazioni", faq: "FAQ", gifts: "Buoni regalo", book: "Prenota ora" }, footer: { tagline: "Una suite romantica privata dedicata al benessere e al tempo insieme.", stay: "Soggiorno & Champagne", contact: "Contatti", rights: "Tutti i diritti riservati.", newsletter: "Newsletter" }, cookies: { button: "Cookie", title: "La tua privacy conta.", body: "I cookie necessari sono sempre attivi. Gli altri restano disattivati senza consenso.", learn: "Scopri di più", analytics: "Analisi", marketing: "Marketing", preferences: "Preferenze", reject: "Rifiuta tutto", save: "Salva", accept: "Accetta tutto" } },
  es: { ...fr, skip: "Ir al contenido", chooseLanguage: "Elegir idioma", openMenu: "Abrir menú", closeMenu: "Cerrar menú", nav: { suite: "La suite", gallery: "Galería", explore: "Explorar", contact: "Contacto", guide: "Guía de viaje", restaurants: "Restaurantes", magazine: "Revista", equipment: "Equipamiento", faq: "FAQ", gifts: "Bonos regalo", book: "Reservar ahora" }, footer: { tagline: "Una suite romántica privada pensada para el bienestar y el tiempo en pareja.", stay: "Estancia y Champaña", contact: "Contacto", rights: "Todos los derechos reservados.", newsletter: "Newsletter" }, cookies: { button: "Cookies", title: "Tu privacidad importa.", body: "Las cookies necesarias funcionan siempre. Las demás permanecen desactivadas sin tu consentimiento.", learn: "Más información", analytics: "Analítica", marketing: "Marketing", preferences: "Preferencias", reject: "Rechazar todo", save: "Guardar", accept: "Aceptar todo" } },
  pt: { ...fr, skip: "Ir para o conteúdo", chooseLanguage: "Escolher idioma", openMenu: "Abrir menu", closeMenu: "Fechar menu", nav: { suite: "A suite", gallery: "Galeria", explore: "Explorar", contact: "Contacto", guide: "Guia de viagem", restaurants: "Restaurantes", magazine: "Revista", equipment: "Equipamentos", faq: "FAQ", gifts: "Vales oferta", book: "Reservar agora" }, footer: { tagline: "Uma suite romântica privativa pensada para o bem-estar e o tempo a dois.", stay: "Estadia e Champagne", contact: "Contactos", rights: "Todos os direitos reservados.", newsletter: "Newsletter" }, cookies: { button: "Cookies", title: "A sua privacidade importa.", body: "Os cookies necessários funcionam sempre. Os restantes ficam desativados sem o seu consentimento.", learn: "Saber mais", analytics: "Audiência", marketing: "Marketing", preferences: "Preferências", reject: "Recusar tudo", save: "Guardar", accept: "Aceitar tudo" } },
};

export function getUiDictionary(locale: Locale): UiDictionary {
  return uiDictionaries[locale] ?? fr;
}
