import { BarChart3, BadgePercent, CheckCircle2, Mail, MapPin, Megaphone, Search, Share2 } from "lucide-react";
import { requireAdmin } from "@/lib/admin/auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { analyticsConfig } from "@/lib/analytics/providers";
import { hasLocalSeo, siteConfig } from "@/lib/site-config";

export default async function Marketing() { await requireAdmin(); const db = createAdminClient(); const [{ data: promotions }, { data: codes }] = await Promise.all([db.from("promotions").select("id,name,discount_percent,start_date,end_date,active").order("start_date", { ascending: false }), db.from("promo_codes").select("id,code,discount_percent,uses,max_uses,active").order("code")]); const channels = [{ label: "Google Analytics", connected: Boolean(analyticsConfig.googleAnalyticsId), icon: BarChart3 }, { label: "Search Console", connected: Boolean(analyticsConfig.searchConsoleVerification), icon: Search }, { label: "Meta Pixel", connected: Boolean(analyticsConfig.metaPixelId), icon: Share2 }, { label: "SEO local", connected: hasLocalSeo, icon: MapPin }]; return <><AdminPageHeader eyebrow="Marketing" title="Acquisition & fidélisation" description="Centralisez mesure d’audience, référencement local, campagnes et offres commerciales." />
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{channels.map((channel) => <article key={channel.label} className="rounded-[1.4rem] border border-white/[.08] bg-[#121212] p-5"><div className="flex items-center justify-between"><channel.icon className="size-5 text-[#C9A86A]" /><span className={`size-2 rounded-full ${channel.connected ? "bg-emerald-400" : "bg-orange-300"}`} /></div><h2 className="mt-5 text-sm">{channel.label}</h2><p className="mt-1 text-[10px] text-white/35">{channel.connected ? "Connecté et soumis au consentement" : "Configuration requise"}</p></article>)}</section>
  <div className="mt-6 grid gap-5 xl:grid-cols-2"><Panel icon={BadgePercent} title="Codes promotionnels"><div className="space-y-2">{codes?.length ? codes.map((code) => <Row key={code.id} title={code.code} detail={`−${code.discount_percent}% · ${code.uses}/${code.max_uses ?? "∞"} utilisations`} active={code.active} />) : <Empty text="Aucun code promotionnel." />}</div></Panel><Panel icon={Megaphone} title="Campagnes"><div className="space-y-2">{promotions?.length ? promotions.map((promotion) => <Row key={promotion.id} title={promotion.name} detail={`−${promotion.discount_percent}% · ${promotion.start_date} → ${promotion.end_date}`} active={promotion.active} />) : <Empty text="Aucune campagne planifiée." />}</div></Panel><Panel icon={Mail} title="Newsletter"><Empty text="Resend est prêt. Importez une audience consentie pour lancer votre première newsletter." /></Panel><Panel icon={MapPin} title="SEO local"><p className="text-sm text-white/50">{hasLocalSeo ? `${siteConfig.commercialName} est configuré pour ${siteConfig.city}, ${siteConfig.department}.` : "Renseignez la ville et le département dans la configuration publique pour activer les signaux SEO locaux."}</p></Panel></div>
  </>; }
function Panel({ icon: Icon, title, children }: { icon: typeof Mail; title: string; children: React.ReactNode }) { return <section className="rounded-[1.5rem] border border-white/[.08] bg-[#121212] p-5"><h2 className="flex items-center gap-2 font-heading text-2xl"><Icon className="size-4 text-[#C9A86A]" />{title}</h2><div className="mt-5">{children}</div></section>; }
function Row({ title, detail, active }: { title: string; detail: string; active: boolean }) { return <article className="flex items-center gap-3 rounded-xl bg-white/[.03] p-3"><CheckCircle2 className={`size-4 ${active ? "text-emerald-300" : "text-white/20"}`} /><div className="min-w-0"><p className="text-sm">{title}</p><p className="truncate text-[10px] text-white/35">{detail}</p></div></article>; }
function Empty({ text }: { text: string }) { return <p className="rounded-xl border border-dashed border-white/10 p-5 text-sm text-white/35">{text}</p>; }
