"use client";
import { useState, type FormEvent } from "react";
type Errors = Partial<Record<"name" | "email" | "phone" | "message", string>>;
export function ContactForm() {
  const [errors,setErrors]=useState<Errors>({}),[sent,setSent]=useState(false),[pending,setPending]=useState(false),[serverError,setServerError]=useState("");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form),next:Errors={};const name=String(data.get("name")??"").trim(),email=String(data.get("email")??"").trim(),phone=String(data.get("phone")??"").trim(),message=String(data.get("message")??"").trim();if(name.length<2)next.name="Indiquez votre nom.";if(!/^\S+@\S+\.\S+$/.test(email))next.email="Saisissez une adresse email valide.";if(phone&&phone.length<6)next.phone="Saisissez un numéro de téléphone valide.";if(message.length<10)next.message="Votre message doit contenir au moins 10 caractères.";setErrors(next);setServerError("");if(Object.keys(next).length)return;setPending(true);try{const response=await fetch("/api/contact",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,email,phone:phone||undefined,message,website:String(data.get("website")??"")})});const result=await response.json();if(!response.ok)throw new Error(result.error);setSent(true);form.reset()}catch(error){setServerError(error instanceof Error?error.message:"Le message n’a pas pu être envoyé.")}finally{setPending(false)}}
  if(sent)return <div role="status" className="border border-[#C9A86A]/40 bg-[#C9A86A]/10 p-8"><h2 className="font-heading text-3xl">Merci pour votre message.</h2><p className="mt-3 leading-7 text-white/65">Votre message a bien été transmis.</p><button onClick={()=>setSent(false)} className="mt-5 text-sm text-[#C9A86A] underline">Écrire un autre message</button></div>;
  const field="mt-2 w-full border border-white/15 bg-[#121212] px-4 py-3 text-white";return <form onSubmit={submit} noValidate className="grid gap-5 sm:grid-cols-2"><label className="text-sm">Nom *<input name="name" autoComplete="name" aria-invalid={!!errors.name} aria-describedby="name-error" className={field}/>{errors.name&&<span id="name-error" className="mt-2 block text-xs text-red-300">{errors.name}</span>}</label><label className="text-sm">Email *<input name="email" type="email" autoComplete="email" aria-invalid={!!errors.email} aria-describedby="email-error" className={field}/>{errors.email&&<span id="email-error" className="mt-2 block text-xs text-red-300">{errors.email}</span>}</label><label className="text-sm sm:col-span-2">Téléphone<input name="phone" type="tel" autoComplete="tel" aria-invalid={!!errors.phone} aria-describedby="phone-error" className={field}/>{errors.phone&&<span id="phone-error" className="mt-2 block text-xs text-red-300">{errors.phone}</span>}</label><label className="text-sm sm:col-span-2">Message *<textarea name="message" rows={6} aria-invalid={!!errors.message} aria-describedby="message-error" className={field}/>{errors.message&&<span id="message-error" className="mt-2 block text-xs text-red-300">{errors.message}</span>}</label><label className="sr-only" aria-hidden="true">Site web<input name="website" tabIndex={-1} autoComplete="off"/></label>{serverError&&<p role="alert" className="text-sm text-red-300 sm:col-span-2">{serverError}</p>}<button disabled={pending} className="min-h-12 bg-[#C9A86A] px-6 text-sm font-semibold uppercase tracking-[.16em] text-black disabled:opacity-50 sm:col-span-2">{pending?"Envoi…":"Envoyer le message"}</button></form>;
}
