export type LocalCity = {
  slug: string; name: string; postal: string; drive: string; distance: string;
  region: string; angle: string; landmark: string; walk: string;
  activities: readonly string[]; restaurants: readonly string[]; image: string; imagePosition: string;
};

const img = ["lit.webp","entree2.webp","salledebain.webp","sauna.webp","entree1.webp","salledebainviolet.webp","saunaviolet.webp","douche.webp","doucheviolet.webp"];
const rows: Omit<LocalCity,"image"|"imagePosition">[] = [
 {slug:"avize",name:"Avize",postal:"51190",drive:"sur place",distance:"moins de 1 km",region:"Côte des Blancs",angle:"un séjour sans trajet après votre arrivée",landmark:"le parc Vix et les coteaux Grand Cru",walk:"une promenade entre le village, les vignes et le belvédère",activities:["Parc Vix","circuit dans les vignes Grand Cru","dégustation chez un vigneron sur rendez-vous"],restaurants:["Les Avisés à Avize","une table à Épernay","un dîner champenois réservé à l’avance"]},
 {slug:"epernay",name:"Épernay",postal:"51200",drive:"environ 15 minutes",distance:"11 km",region:"capitale de l’avenue de Champagne",angle:"associer l’effervescence d’Épernay au calme d’Avize",landmark:"l’avenue de Champagne et ses grandes maisons",walk:"une flânerie sur l’avenue de Champagne puis dans le centre",activities:["Avenue de Champagne","musée du vin de Champagne et d’Archéologie régionale","ballon captif selon la météo"],restaurants:["Symbiose","La Grillade Gourmande","Cook’in"]},
 {slug:"reims",name:"Reims",postal:"51100",drive:"environ 40 minutes",distance:"35 km",region:"cité des sacres",angle:"prolonger une journée culturelle par une nuit confidentielle",landmark:"la cathédrale Notre-Dame et les crayères",walk:"un parcours de la cathédrale aux maisons de champagne",activities:["Cathédrale Notre-Dame","palais du Tau","visite de crayères sur réservation"],restaurants:["Brasserie Le Jardin","La Table Saint Thomas","La Grande Georgette"]},
 {slug:"chalons-en-champagne",name:"Châlons-en-Champagne",postal:"51000",drive:"environ 35 minutes",distance:"32 km",region:"ville d’eau et de jardins",angle:"quitter les canaux pour une soirée spa en duo",landmark:"les canaux, le Jard et la collégiale Notre-Dame-en-Vaux",walk:"une boucle entre le Grand Jard et le centre historique",activities:["balade en barque selon la saison","collégiale Notre-Dame-en-Vaux","jardins du Jard"],restaurants:["une table du centre historique","une brasserie près du Jard","un restaurant à Épernay sur le trajet"]},
 {slug:"vertus",name:"Vertus",postal:"51130",drive:"environ 15 minutes",distance:"13 km",region:"Côte des Blancs méridionale",angle:"relier patrimoine viticole et détente privative",landmark:"le puits Saint-Martin et les coteaux",walk:"une marche vers le mont Aimé ou dans les rues anciennes",activities:["circuit du patrimoine de Vertus","belvédères du mont Aimé","rencontre avec un vigneron"],restaurants:["une table à Vertus","Les Avisés à Avize","une adresse à Épernay"]},
 {slug:"cramant",name:"Cramant",postal:"51530",drive:"environ 7 minutes",distance:"5 km",region:"Côte des Blancs Grand Cru",angle:"vivre une échappée au cœur du chardonnay",landmark:"le belvédère et la bouteille monumentale",walk:"une boucle panoramique au-dessus des vignes",activities:["belvédère de Cramant","route touristique du Champagne","dégustation sur rendez-vous"],restaurants:["Les Avisés à Avize","une table à Épernay","un repas chez un restaurateur de la Côte des Blancs"]},
 {slug:"le-mesnil-sur-oger",name:"Le Mesnil-sur-Oger",postal:"51190",drive:"environ 8 minutes",distance:"7 km",region:"Côte des Blancs Grand Cru",angle:"composer une parenthèse autour des grands chardonnays",landmark:"les clos, caves et perspectives viticoles",walk:"une promenade calme entre église, maisons et vignoble",activities:["musée de la Vigne et du Vin selon ouverture","jardin de vignes","visite de domaine sur rendez-vous"],restaurants:["une table de la Côte des Blancs","Les Avisés à Avize","une adresse à Vertus"]},
 {slug:"ay-champagne",name:"Aÿ-Champagne",postal:"51160",drive:"environ 25 minutes",distance:"20 km",region:"vallée de la Marne Grand Cru",angle:"passer des coteaux historiques à une suite avec spa",landmark:"les coteaux d’Aÿ et la Cité du Champagne",walk:"une balade entre canal, maisons de champagne et coteaux",activities:["Cité du Champagne","parcours dans les coteaux historiques","voie verte le long du canal"],restaurants:["une table à Aÿ","Le Royal à Champillon","Symbiose à Épernay"]},
 {slug:"dormans",name:"Dormans",postal:"51700",drive:"environ 45 minutes",distance:"43 km",region:"vallée de la Marne occidentale",angle:"transformer une escapade mémorielle en pause romantique",landmark:"le mémorial des batailles de la Marne",walk:"une promenade dans le parc du château et près de la Marne",activities:["mémorial de Dormans","parc du château","route touristique de la vallée de la Marne"],restaurants:["une table à Dormans","une adresse à Épernay","un dîner à Avize sur réservation"]},
 {slug:"sezanne",name:"Sézanne",postal:"51120",drive:"environ 45 minutes",distance:"46 km",region:"Brie champenoise",angle:"allier ruelles anciennes et bien-être à deux",landmark:"les mails plantés et le patrimoine médiéval",walk:"un circuit sous les arbres autour du vieux Sézanne",activities:["circuit des ruelles historiques","église Saint-Denis","vignoble du Sézannais"],restaurants:["une table du centre de Sézanne","une auberge du Sézannais","Les Avisés à l’arrivée à Avize"]},
 {slug:"montmirail",name:"Montmirail",postal:"51210",drive:"environ 1 heure",distance:"65 km",region:"Brie champenoise",angle:"offrir une destination intime après une journée d’histoire",landmark:"le château, les remparts et la mémoire napoléonienne",walk:"une découverte des ruelles, de l’église et de la tour de Montléan",activities:["château de Montmirail selon accès","site de la bataille de 1814","vallée du Petit Morin"],restaurants:["une auberge de Montmirail","une table à Sézanne","un dîner à Avize"]},
 {slug:"fismes",name:"Fismes",postal:"51170",drive:"environ 55 minutes",distance:"53 km",region:"vallée de la Vesle",angle:"changer de rythme entre patrimoine de mémoire et vignoble",landmark:"le pont mémorial américain et la Vesle",walk:"une promenade le long de la Vesle et dans le centre",activities:["pont mémorial américain","balade dans la vallée de la Vesle","halte à Reims sur l’itinéraire"],restaurants:["une table à Fismes","La Table Saint Thomas à Reims","une adresse à Épernay"]},
 {slug:"tinqueux",name:"Tinqueux",postal:"51430",drive:"environ 40 minutes",distance:"37 km",region:"ouest rémois",angle:"s’éloigner rapidement de la ville pour retrouver l’intimité",landmark:"la proximité immédiate de Reims et de la montagne de Reims",walk:"une parenthèse urbaine avant de rejoindre les coteaux",activities:["centre historique de Reims","parc de Champagne","route de la montagne de Reims"],restaurants:["L’Assiette Champenoise","une brasserie rémoise","Les Avisés à Avize"]},
 {slug:"champillon",name:"Champillon",postal:"51160",drive:"environ 25 minutes",distance:"22 km",region:"balcon sur la vallée de la Marne",angle:"poursuivre une vue panoramique par une nuit sensorielle",landmark:"les panoramas sur Épernay et la vallée",walk:"une marche sur les hauteurs entre vignes et lisières",activities:["points de vue de Champillon","route touristique du Champagne","halte à Hautvillers"],restaurants:["Le Royal à Champillon","une table à Hautvillers","Symbiose à Épernay"]},
 {slug:"dizy",name:"Dizy",postal:"51530",drive:"environ 20 minutes",distance:"17 km",region:"porte de la vallée de la Marne",angle:"relier facilement Épernay, Hautvillers et Avize",landmark:"le canal latéral à la Marne et les coteaux voisins",walk:"une balade au bord du canal avant de gagner Hautvillers",activities:["voie verte du canal","Hautvillers à proximité","avenue de Champagne"],restaurants:["une table à Dizy","une adresse à Hautvillers","La Grillade Gourmande à Épernay"]},
 {slug:"pierry",name:"Pierry",postal:"51530",drive:"environ 15 minutes",distance:"12 km",region:"Coteaux Sud d’Épernay",angle:"passer d’un village viticole à une bulle privée",landmark:"le château de Pierry et les demeures de négociants",walk:"un circuit du patrimoine entre cours et coteaux",activities:["château de Pierry selon programmation","route des Coteaux Sud","avenue de Champagne voisine"],restaurants:["une table à Pierry","Symbiose à Épernay","Les Avisés à Avize"]},
 {slug:"magenta",name:"Magenta",postal:"51530",drive:"environ 20 minutes",distance:"16 km",region:"rive de Marne face à Épernay",angle:"retrouver le calme après une journée entre canal et avenue",landmark:"la Marne, le canal et la proximité d’Épernay",walk:"une traversée douce vers Épernay par les berges",activities:["balade au bord de la Marne","avenue de Champagne","Hautvillers et ses coteaux"],restaurants:["une adresse à Épernay","La Grillade Gourmande","Cook’in"]},
 {slug:"oiry",name:"Oiry",postal:"51530",drive:"environ 8 minutes",distance:"7 km",region:"plaine viticole de la Côte des Blancs",angle:"choisir une escapade très proche sans renoncer au dépaysement",landmark:"les vues ouvertes sur les coteaux de la Côte des Blancs",walk:"une promenade rurale face aux villages Grand Cru",activities:["route touristique du Champagne","découverte d’Avize","belvédère de Cramant"],restaurants:["Les Avisés à Avize","une table à Épernay","une adresse à Vertus"]},
 {slug:"mareuil-sur-ay",name:"Mareuil-sur-Aÿ",postal:"51160",drive:"environ 20 minutes",distance:"18 km",region:"vallée de la Marne",angle:"faire dialoguer canal, vignoble et spa privatif",landmark:"le canal, le château et les coteaux d’Aÿ-Champagne",walk:"une promenade le long de l’eau puis dans le vignoble",activities:["balade au canal","visite de domaine sur rendez-vous","Cité du Champagne à Aÿ"],restaurants:["une table à Aÿ-Champagne","Le Royal à Champillon","une adresse à Épernay"]},
 {slug:"hautvillers",name:"Hautvillers",postal:"51160",drive:"environ 25 minutes",distance:"22 km",region:"berceau historique du champagne",angle:"prolonger une journée iconique par une soirée confidentielle",landmark:"l’abbatiale et les enseignes en fer forgé",walk:"une déambulation dans les ruelles puis vers les panoramas",activities:["abbatiale Saint-Sindulphe","coteaux historiques UNESCO","points de vue sur la vallée"],restaurants:["une table à Hautvillers","Le Royal à Champillon","Symbiose à Épernay"]},
 {slug:"chouilly",name:"Chouilly",postal:"51530",drive:"environ 10 minutes",distance:"8 km",region:"Côte des Blancs Grand Cru",angle:"rester au plus près des vignes tout en changeant d’univers",landmark:"le jardin de vignes et les coteaux de chardonnay",walk:"une boucle entre village, jardin pédagogique et vignes",activities:["jardin de vignes","route touristique","avenue de Champagne à proximité"],restaurants:["Les Avisés à Avize","une table à Épernay","une adresse à Pierry"]},
 {slug:"blancs-coteaux-oger",name:"Oger",postal:"51190",drive:"environ 5 minutes",distance:"4 km",region:"Côte des Blancs Grand Cru",angle:"s’offrir une nuit à quelques minutes au cœur du vignoble",landmark:"les rues fleuries et les coteaux Grand Cru",walk:"une balade villageoise tournée vers les vignes",activities:["patrimoine viticole d’Oger","forêt et coteaux","visite de vigneron sur rendez-vous"],restaurants:["Les Avisés à Avize","une table à Vertus","une adresse à Épernay"]},
 {slug:"bouzy",name:"Bouzy",postal:"51150",drive:"environ 25 minutes",distance:"22 km",region:"montagne de Reims Grand Cru",angle:"passer du pinot noir à la douceur d’une suite spa",landmark:"les coteaux Grand Cru et la tradition du Bouzy rouge",walk:"une promenade viticole avec vues sur la plaine",activities:["sentiers viticoles","dégustation sur rendez-vous","phare de Verzenay sur l’itinéraire"],restaurants:["une table à Bouzy","Le Royal à Champillon","Les Avisés à Avize"]},
 {slug:"ambonnay",name:"Ambonnay",postal:"51150",drive:"environ 25 minutes",distance:"24 km",region:"montagne de Reims Grand Cru",angle:"conjuguer découverte du pinot noir et détente privative",landmark:"l’église, les maisons de champagne et les coteaux",walk:"une boucle tranquille au pied de la montagne de Reims",activities:["circuit dans les vignes","visite de domaine","forêt de Verzy à proximité"],restaurants:["une table d’Ambonnay","Le Royal à Champillon","une adresse à Avize"]},
 {slug:"verzenay",name:"Verzenay",postal:"51360",drive:"environ 35 minutes",distance:"31 km",region:"montagne de Reims",angle:"relier un panorama spectaculaire à une nuit en amoureux",landmark:"le phare et le musée de la Vigne",walk:"une marche du village au phare à travers les coteaux",activities:["phare de Verzenay","musée de la Vigne","faux de Verzy"],restaurants:["une table sur la montagne de Reims","Le Relais de Sillery","Les Avisés à Avize"]},
 {slug:"verzy",name:"Verzy",postal:"51380",drive:"environ 35 minutes",distance:"31 km",region:"montagne de Reims forestière",angle:"passer d’une forêt singulière à une ambiance feutrée",landmark:"les faux de Verzy et leurs hêtres tortillards",walk:"un parcours forestier balisé dans la réserve biologique",activities:["faux de Verzy","sentiers du parc naturel régional","phare de Verzenay"],restaurants:["une table de la montagne de Reims","Le Relais de Sillery","une adresse à Bouzy"]},
 {slug:"rilly-la-montagne",name:"Rilly-la-Montagne",postal:"51500",drive:"environ 35 minutes",distance:"32 km",region:"versant nord de la montagne de Reims",angle:"faire suivre les caves et coteaux d’un cocon pour deux",landmark:"les maisons de champagne et la lisière forestière",walk:"une promenade entre village viticole et bois",activities:["visite de cave sur rendez-vous","randonnée en montagne de Reims","halte à Reims"],restaurants:["Couvert de Vignes à Chigny-les-Roses","une table à Rilly","Les Avisés à Avize"]},
 {slug:"avenay-val-dor",name:"Avenay-Val-d’Or",postal:"51160",drive:"environ 25 minutes",distance:"22 km",region:"vallée de la Marne et montagne de Reims",angle:"s’échapper entre forêt, vignes et spa",landmark:"les coteaux et la vallée de la Livre",walk:"une balade sur les chemins reliant vigne et sous-bois",activities:["sentiers viticoles","réserve des pâtis","Aÿ-Champagne à proximité"],restaurants:["une table à Aÿ","Le Royal à Champillon","une adresse à Épernay"]},
 {slug:"tours-sur-marne",name:"Tours-sur-Marne",postal:"51150",drive:"environ 20 minutes",distance:"18 km",region:"carrefour de la Marne et des coteaux",angle:"rejoindre rapidement une suite intime depuis la vallée",landmark:"le canal et les coteaux de la montagne de Reims",walk:"une promenade au fil de l’eau avec vue sur le vignoble",activities:["voie verte du canal","Bouzy et Ambonnay","route touristique du Champagne"],restaurants:["une table à Tours-sur-Marne","une adresse à Bouzy","Les Avisés à Avize"]},
 {slug:"conde-sur-marne",name:"Condé-sur-Marne",postal:"51150",drive:"environ 25 minutes",distance:"24 km",region:"confluence des canaux champenois",angle:"troquer les paysages d’eau contre une soirée sensorielle",landmark:"l’église Saint-Rémi et les voies d’eau",walk:"une balade près du canal latéral à la Marne",activities:["patrimoine de Condé","voie verte","coteaux d’Ambonnay"],restaurants:["une table dans le secteur de Condé","Le Relais de Sillery","une adresse à Bouzy"]},
 {slug:"sillery",name:"Sillery",postal:"51500",drive:"environ 35 minutes",distance:"32 km",region:"plaine rémoise et canal",angle:"quitter l’agglomération rémoise pour une nuit à deux",landmark:"le canal de l’Aisne à la Marne et les coteaux proches",walk:"une promenade sur la voie verte au bord de l’eau",activities:["voie verte","fort de la Pompelle à proximité","montagne de Reims"],restaurants:["Le Relais de Sillery","une table à Reims","Les Avisés à Avize"]},
 {slug:"bezannes",name:"Bezannes",postal:"51430",drive:"environ 35 minutes",distance:"32 km",region:"porte sud de Reims",angle:"transformer un départ facile en véritable déconnexion",landmark:"la proximité de la gare Champagne-Ardenne TGV",walk:"une halte rémoise avant la route panoramique vers Avize",activities:["centre de Reims","parc de Champagne","route de la Côte des Blancs"],restaurants:["Bouche B","une table à Reims","Les Avisés à Avize"]},
 {slug:"taissy",name:"Taissy",postal:"51500",drive:"environ 35 minutes",distance:"31 km",region:"sud-est rémois",angle:"rejoindre un refuge intime sans long voyage",landmark:"la vallée de la Vesle et la proximité du vignoble",walk:"une promenade douce avant de gagner la montagne de Reims",activities:["fort de la Pompelle","parc de Champagne","coteaux de Sillery"],restaurants:["Le Relais de Sillery","une brasserie à Reims","une table à Avize"]},
 {slug:"cumieres",name:"Cumières",postal:"51480",drive:"environ 30 minutes",distance:"26 km",region:"vallée de la Marne",angle:"prolonger les berges et coteaux par une soirée spa",landmark:"la halte nautique et les coteaux historiques",walk:"une balade sur les berges puis vers Hautvillers",activities:["voie verte de la vallée","statues du travail de la vigne","Hautvillers à proximité"],restaurants:["une table à Cumières","une adresse à Hautvillers","Symbiose à Épernay"]},
 {slug:"damery",name:"Damery",postal:"51480",drive:"environ 30 minutes",distance:"29 km",region:"vallée de la Marne",angle:"associer promenade fluviale et nuit romantique",landmark:"la Marne, le pont et le patrimoine roman",walk:"une boucle sur les berges et dans le bourg",activities:["voie verte","église Saint-Georges","route touristique de la vallée"],restaurants:["une table à Damery","une adresse à Épernay","Le Royal à Champillon"]},
 {slug:"chatillon-sur-marne",name:"Châtillon-sur-Marne",postal:"51700",drive:"environ 40 minutes",distance:"40 km",region:"vallée de la Marne panoramique",angle:"faire suivre un grand panorama d’une parenthèse privée",landmark:"la statue d’Urbain II et le panorama sur la vallée",walk:"une montée dans les ruelles jusqu’au belvédère",activities:["statue d’Urbain II","point de vue sur la vallée","route du Champagne"],restaurants:["une table à Châtillon","une adresse à Dormans","un dîner à Épernay"]},
 {slug:"orbais-labbaye",name:"Orbais-l’Abbaye",postal:"51270",drive:"environ 35 minutes",distance:"35 km",region:"vallée du Surmelin",angle:"passer d’un patrimoine gothique discret à un refuge contemporain",landmark:"l’abbatiale Saint-Pierre et Saint-Paul",walk:"une découverte du bourg et des paysages du Surmelin",activities:["abbatiale d’Orbais","randonnée dans la vallée","route vers la Côte des Blancs"],restaurants:["une auberge de la vallée","une table à Vertus","Les Avisés à Avize"]},
 {slug:"esternay",name:"Esternay",postal:"51310",drive:"environ 55 minutes",distance:"58 km",region:"Brie champenoise",angle:"changer complètement de décor le temps d’une nuit",landmark:"les paysages agricoles, fermes briardes et forêts",walk:"une promenade rurale vers la forêt de la Traconne",activities:["forêt de la Traconne","patrimoine briard","halte à Sézanne"],restaurants:["une table à Esternay","une adresse à Sézanne","un dîner à Avize"]},
 {slug:"chateau-thierry",name:"Château-Thierry",postal:"02400",drive:"environ 1 heure",distance:"67 km",region:"vallée de la Marne dans l’Aisne",angle:"relier la cité de La Fontaine aux grands crus de la Côte des Blancs",landmark:"le château médiéval et le musée Jean de La Fontaine",walk:"une montée au château avec vue sur la Marne",activities:["musée Jean de La Fontaine","ruines du château","route touristique vers Dormans"],restaurants:["une table à Château-Thierry","une adresse à Dormans","un dîner à Épernay"]},
 {slug:"vitry-le-francois",name:"Vitry-le-François",postal:"51300",drive:"environ 55 minutes",distance:"58 km",region:"porte du Perthois",angle:"s’offrir une rupture élégante entre ville et vignoble",landmark:"la place d’Armes et la collégiale Notre-Dame",walk:"un parcours dans le plan urbain classique autour de la place",activities:["place d’Armes","collégiale Notre-Dame","halte à Châlons-en-Champagne"],restaurants:["une table à Vitry-le-François","une adresse à Châlons","un dîner à Avize"]},
 {slug:"epernay-coteaux-sud",name:"Moussy",postal:"51530",drive:"environ 15 minutes",distance:"11 km",region:"Coteaux Sud d’Épernay",angle:"rejoindre très vite un espace de détente entièrement privé",landmark:"les coteaux, le Cubry et la proximité d’Épernay",walk:"une balade entre village et chemins viticoles",activities:["route des Coteaux Sud","avenue de Champagne","Pierry et son patrimoine"],restaurants:["une table à Épernay","une adresse à Pierry","Les Avisés à Avize"]},
];

export const localCities: LocalCity[] = rows.map((city,index)=>({...city,image:`/images/optimized/${img[index%img.length]}`,imagePosition:["object-center","object-[center_40%]","object-[center_60%]","object-left","object-right"][index%5]}));
export const getLocalCity=(slug:string)=>localCities.find(city=>city.slug===slug);
