import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, extname, join, relative } from "node:path";
const root=process.cwd();
const walk=(dir)=>existsSync(dir)?readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.name==="node_modules"||e.name===".next"?[]:e.isDirectory()?walk(join(dir,e.name)):[join(dir,e.name)]):[];
const source=[...walk(join(root,"app")),...walk(join(root,"lib")),...walk(join(root,"components"))].filter(f=>[".ts",".tsx"].includes(extname(f)));
const has=(path)=>existsSync(join(root,path));
const content=(path)=>has(path)?readFileSync(join(root,path),"utf8"):"";
const checks=[];
const check=(area,name,ok,evidence,level="required")=>checks.push({area,name,status:!ok?"fail":level==="external"?"manual":"pass",evidence});
check("quality","Lint configuré",has("eslint.config.mjs"),"eslint.config.mjs");
check("quality","Tests automatiques",has("tests/release.test.mjs"),"npm test");
check("seo","Robots et sitemap",has("app/robots.ts")&&has("app/sitemap.ts"),"MetadataRoute");
check("seo","Audit SEO",has("reports/seo-audit.json"),"reports/seo-audit.json");
check("schema","Validation JSON-LD",has("scripts/validate-structured-data.mjs"),"npm run validate:schema");
check("performance","Budgets statiques",has("performance-budget.json")&&has("reports/performance.json"),"npm run performance:audit");
check("performance","Lighthouse CI",has("lighthouserc.json")&&has(".github/workflows/performance.yml"),"Lighthouse réel en CI");
check("security","En-têtes de sécurité",/Content-Security-Policy/.test(content("next.config.ts")),"CSP, HSTS, nosniff");
check("security","Secrets ignorés",/\.env\*/.test(content(".gitignore")),".gitignore");
check("accessibility","Lint accessibilité",/eslint-config-next/.test(content("package.json")),"eslint-config-next");
check("responsive","Points de rupture responsifs",source.some(f=>/\b(sm|md|lg|xl):/.test(readFileSync(f,"utf8"))),"Tailwind responsive");
check("pwa","PWA hors-ligne",has("app/manifest.ts")&&has("public/sw.js")&&has("app/offline/page.tsx"),"manifest + service worker + offline");
check("errors","Fallback global",has("app/error.tsx")&&has("app/global-error.tsx"),"Error boundaries accessibles");
check("monitoring","Instrumentation serveur",has("instrumentation.ts")&&has("app/api/health/route.ts"),"onRequestError + health");
check("backup","Sauvegarde et restauration",has("scripts/backup-supabase.ps1")&&has("scripts/restore-supabase.ps1"),"pg_dump/pg_restore");
for(const [name,needle] of [["Supabase","SUPABASE_SERVICE_ROLE_KEY"],["Stripe","STRIPE_WEBHOOK_SECRET"],["Resend","RESEND_API_KEY"],["iCal","BOOKING_ICAL_URL"],["Google","GOOGLE_BUSINESS_CLIENT_ID"]])check("integrations",name,content(".env.example").includes(needle),`${needle} documenté`,"external");
check("analytics","Consentement et collecte",has("components/analytics")&&has("app/api/analytics"),"collecte first-party avec consentement");
const failures=checks.filter(c=>c.status==="fail"),manual=checks.filter(c=>c.status==="manual");
const report={version:"1.0.0",generatedAt:new Date().toISOString(),status:failures.length?"fail":"pass",summary:{passed:checks.filter(c=>c.status==="pass").length,failed:failures.length,manual:manual.length,total:checks.length},checks,largestSources:source.map(f=>({file:relative(root,f).replaceAll("\\","/"),bytes:statSync(f).size})).sort((a,b)=>b.bytes-a.bytes).slice(0,15),limitations:["Les scores Lighthouse sont produits par un navigateur en CI, jamais simulés.","Les intégrations externes exigent une recette en préproduction avec les identifiants du propriétaire.","La sauvegarde n’est valide qu’après un test de restauration isolé."]};
const destination=join(root,"reports","release-audit.json");mkdirSync(dirname(destination),{recursive:true});writeFileSync(destination,JSON.stringify(report,null,2)+"\n");
const securityChecks=checks.filter(c=>["security","errors","backup","monitoring"].includes(c.area));
writeFileSync(join(root,"reports","security-audit.json"),JSON.stringify({generatedAt:report.generatedAt,status:securityChecks.some(c=>c.status==="fail")?"fail":"pass",checks:securityChecks,residualRisks:["La limitation en mémoire n’est pas distribuée entre les instances Vercel.","Les politiques RLS doivent être testées après chaque migration.","Les webhooks Stripe et crons exigent une vérification avec secrets réels en préproduction."]},null,2)+"\n");
writeFileSync(join(root,"reports","lighthouse.json"),JSON.stringify({generatedAt:report.generatedAt,status:"pending-ci",configuration:"lighthouserc.json",workflow:".github/workflows/performance.yml",targets:["/","/la-suite","/reservation","/love-room/avize"],thresholds:{performance:100,accessibility:100,bestPractices:100,seo:100,lcpMs:2500,cls:0.1,tbtMs:200},note:"Ce fichier décrit la campagne. Les résultats réels sont les artefacts Lighthouse CI, générés avec Chrome après déploiement/build."},null,2)+"\n");
console.log(`Release audit ${report.status}: ${report.summary.passed}/${report.summary.total} contrôles automatiques, ${report.summary.manual} recettes externes`);
if(failures.length)process.exitCode=1;
