import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { JsonLd } from "@/components/seo/json-ld";
import { LanguageSelector } from "@/components/i18n/language-selector";
import { dictionaries, isLocale, languageAlternates, locales } from "@/lib/i18n/config";
import { siteConfig } from "@/lib/site-config";
const sections=["blog","guides","faq"] as const;type Section=typeof sections[number];const isSection=(v:string):v is Section=>(sections as readonly string[]).includes(v);
export const dynamicParams=false;
export function generateStaticParams(){return locales.flatMap(locale=>sections.map(section=>({locale,section})));}
export async function generateMetadata({params}:{params:Promise<{locale:string;section:string}>}):Promise<Metadata>{const {locale,section}=await params;if(!isLocale(locale)||!isSection(section))return{};const d=dictionaries[locale],title=section==="blog"?d.blogTitle:section==="guides"?d.guideTitle:d.faqTitle,path=`/${section}`;return{title:`${title} | Absolu`,description:`${title} — ${d.description}`,alternates:{canonical:`${siteConfig.url}/${locale}${path}`,languages:{...languageAlternates(path),"x-default":`${siteConfig.url}/${section==="guides"?"guide-touristique":section}`}}};}
export default async function LocalSection({params}:{params:Promise<{locale:string;section:string}>}){const {locale,section}=await params;if(!isLocale(locale)||!isSection(section))notFound();const d=dictionaries[locale],items=section==="blog"?d.posts:section==="guides"?d.guides:d.faq.map(x=>x.q),title=section==="blog"?d.blogTitle:section==="guides"?d.guideTitle:d.faqTitle;return <main lang={locale} className="page-shell min-h-screen pb-24 pt-28"><JsonLd data={{"@context":"https://schema.org","@type":section==="faq"?"FAQPage":"CollectionPage",name:title,inLanguage:locale,...(section==="faq"?{mainEntity:d.faq.map(x=>({"@type":"Question",name:x.q,acceptedAnswer:{"@type":"Answer",text:x.a}}))}:{})}}/><header className="flex items-center justify-between"><Link href={`/${locale}`} className="font-heading text-2xl tracking-[.2em]">ABSOLU</Link><LanguageSelector locale={locale}/></header><p className="eyebrow mt-20 text-[#C9A86A]">{d.eyebrow}</p><h1 className="mt-4 font-heading text-7xl">{title}</h1><div className="mt-14 grid gap-5 md:grid-cols-2">{items.map((item,index)=><article key={item} className="rounded-3xl border border-white/10 bg-[#121212] p-7"><span className="text-xs text-[#C9A86A]">0{index+1}</span><h2 className="mt-4 font-heading text-3xl">{item}</h2>{section==="faq"&&<p className="mt-4 leading-7 text-white/50">{d.faq[index].a}</p>}<p className="mt-4 text-sm leading-7 text-white/40">{section!=="faq"&&d.intro}</p></article>)}</div><nav className="mt-16 flex flex-wrap gap-3"><Link href={`/${locale}/blog`} className="rounded-full border border-white/15 px-5 py-3">{d.blogTitle}</Link><Link href={`/${locale}/guides`} className="rounded-full border border-white/15 px-5 py-3">{d.guideTitle}</Link><Link href={`/${locale}/faq`} className="rounded-full border border-white/15 px-5 py-3">FAQ</Link></nav></main>}
