create table public.audit_logs(id uuid primary key default gen_random_uuid(),admin_user_id uuid references auth.users(id) on delete set null,action text not null,entity_type text not null,entity_id text,ip inet,metadata jsonb not null default '{}',created_at timestamptz not null default now());
create table public.seasonal_prices(id uuid primary key default gen_random_uuid(),name text not null,start_date date not null,end_date date not null,price integer not null check(price>=0),active boolean not null default true,created_at timestamptz not null default now(),check(end_date>start_date));
create table public.promotions(id uuid primary key default gen_random_uuid(),name text not null,discount_percent integer not null check(discount_percent between 1 and 100),start_date date not null,end_date date not null,active boolean not null default true,check(end_date>start_date));
create table public.promo_codes(id uuid primary key default gen_random_uuid(),code text not null unique,discount_percent integer not null check(discount_percent between 1 and 100),starts_at timestamptz,ends_at timestamptz,max_uses integer check(max_uses>0),uses integer not null default 0,active boolean not null default true);
create table public.sync_logs(id uuid primary key default gen_random_uuid(),source public.reservation_source not null,status text not null check(status in('success','failed','skipped')),events_count integer not null default 0,error_code text,created_at timestamptz not null default now());
create table public.notifications(id uuid primary key default gen_random_uuid(),kind text not null,title text not null,message text not null,read_at timestamptz,created_at timestamptz not null default now());
create table public.email_logs(id uuid primary key default gen_random_uuid(),reservation_id uuid references public.reservations(id) on delete set null,template text not null,recipient_hash text not null,status text not null check(status in('sent','failed','skipped')),provider_id text,error_code text,created_at timestamptz not null default now());
create table public.login_logs(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete cascade,ip inet,user_agent text,created_at timestamptz not null default now());
create index audit_logs_created_idx on public.audit_logs(created_at desc);create index audit_logs_entity_idx on public.audit_logs(entity_type,entity_id);create index sync_logs_created_idx on public.sync_logs(created_at desc);create index notifications_unread_idx on public.notifications(created_at desc) where read_at is null;create index email_logs_reservation_idx on public.email_logs(reservation_id,created_at desc);
alter table public.audit_logs enable row level security;alter table public.seasonal_prices enable row level security;alter table public.promotions enable row level security;alter table public.promo_codes enable row level security;alter table public.sync_logs enable row level security;alter table public.notifications enable row level security;alter table public.email_logs enable row level security;alter table public.login_logs enable row level security;
create policy "admins manage audit logs" on public.audit_logs for all to authenticated using(public.is_admin()) with check(public.is_admin());create policy "admins manage seasonal prices" on public.seasonal_prices for all to authenticated using(public.is_admin()) with check(public.is_admin());create policy "admins manage promotions" on public.promotions for all to authenticated using(public.is_admin()) with check(public.is_admin());create policy "admins manage promo codes" on public.promo_codes for all to authenticated using(public.is_admin()) with check(public.is_admin());create policy "admins manage sync logs" on public.sync_logs for all to authenticated using(public.is_admin()) with check(public.is_admin());create policy "admins manage notifications" on public.notifications for all to authenticated using(public.is_admin()) with check(public.is_admin());create policy "admins read email logs" on public.email_logs for select to authenticated using(public.is_admin());create policy "admins read login logs" on public.login_logs for select to authenticated using(public.is_admin());
insert into public.settings(key,value) values ('maintenance','{"enabled":false}'),('property','{}'),('social','{}'),('seo','{}'),('branding','{}'),('taxes','{"rate":0}') on conflict(key) do nothing;

create or replace function public.admin_move_reservation(p_id uuid,p_check_in date,p_check_out date) returns boolean language plpgsql security definer set search_path='' as $$
begin
  perform pg_advisory_xact_lock(hashtext('absolu_reservations'));
  if p_check_out<=p_check_in then raise exception 'INVALID_RANGE' using errcode='P0001'; end if;
  if exists(select 1 from public.reservations where id<>p_id and check_in<p_check_out and check_out>p_check_in and (status='confirmed' or (status='pending_payment' and payment_expires_at>now()))) or exists(select 1 from public.blocked_dates where start_date<p_check_out and end_date>p_check_in and not(source='direct' and external_uid=p_id::text)) then raise exception 'DATES_UNAVAILABLE' using errcode='P0001'; end if;
  update public.reservations set check_in=p_check_in,check_out=p_check_out,nights=p_check_out-p_check_in,updated_at=now() where id=p_id and status in('confirmed','pending_payment');
  update public.blocked_dates set start_date=p_check_in,end_date=p_check_out where source='direct' and external_uid=p_id::text;
  return found;
end $$;revoke all on function public.admin_move_reservation from public,anon,authenticated;grant execute on function public.admin_move_reservation to service_role;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('admin-assets','admin-assets',true,5000000,array['image/jpeg','image/png','image/webp','image/svg+xml','image/x-icon']) on conflict(id) do nothing;
create policy "admins manage admin assets" on storage.objects for all to authenticated using(bucket_id='admin-assets' and public.is_admin()) with check(bucket_id='admin-assets' and public.is_admin());
