export type EquipmentStatus="confirmed"|"to-confirm";
export type EquipmentItem={slug:string;name:string;shortName:string;category:"Bien-être"|"Confort"|"Ambiance"|"Services";status:EquipmentStatus;headline:string;description:string;advice:string;detail:string;image:string;gallery:readonly string[];features:readonly string[];faq:readonly [string,string][]};
const images={bath:"/images/optimized/salledebain.webp",bathMood:"/images/optimized/salledebainviolet.webp",sauna:"/images/optimized/sauna.webp",saunaMood:"/images/optimized/saunaviolet.webp",bed:"/images/optimized/lit.webp",entry:"/images/optimized/entree1.webp",entryAlt:"/images/optimized/entree2.webp",shower:"/images/optimized/douche.webp",showerMood:"/images/optimized/doucheviolet.webp"};
const faq=(name:string,status:EquipmentStatus,detail:string):readonly [string,string][]=>[[`${name} est-il inclus dans la Suite Absolu ?`,status==="confirmed"?`Oui. ${detail}`:`La présence ou la configuration exacte de ${name.toLowerCase()} doit être confirmée avant la réservation. Cette page ne le présente pas comme une prestation garantie.`],["Cet équipement est-il privatif ?",status==="confirmed"?"Lorsqu’il se trouve dans la suite, il est exclusivement réservé aux occupants pendant leur séjour.":"Demandez une confirmation écrite sur sa disponibilité et ses conditions d’utilisation avant le séjour."],["Comment vérifier les informations avant de réserver ?","Consultez le récapitulatif de réservation et contactez directement Absolu si une caractéristique précise conditionne votre séjour."],["Où se trouve la Suite Absolu ?","La suite se trouve au 36 rue Pasteur, 51190 Avize, au cœur de la Côte des Blancs, près d’Épernay."]];
const raw=[
 ["baignoire-balneo","Baignoire balnéo","Balnéo","Bien-être","confirmed","Un bain à deux, sans créneau partagé.","La baignoire balnéo privative crée un temps de détente directement dans la suite.","Hydratez-vous, choisissez une température confortable et alternez bain et repos.","La baignoire balnéo est exclusivement réservée aux occupants de la suite.",images.bath,[images.bath,images.bathMood,images.shower],["Privative","Pensée pour deux","Deux ambiances lumineuses"]],
 ["sauna","Sauna infrarouge","Sauna","Bien-être","confirmed","Une chaleur douce au cœur de la suite.","Le sauna infrarouge privatif permet de construire un rituel de chaleur et de repos à votre rythme.","Privilégiez des sessions raisonnables, buvez de l’eau et respectez toute contre-indication médicale.","Le sauna infrarouge est intégré à l’espace privatif.",images.sauna,[images.sauna,images.saunaMood,images.entry],["Privatif","Infrarouge","Disponible dans la suite"]],
 ["lit-king-size","Lit King Size","Literie","Confort","to-confirm","Une literie confortable, dimensions à confirmer.","La suite dispose d’un grand lit double et d’une literie haut de gamme ; l’appellation King Size n’est pas garantie dans les données actuelles.","Si les dimensions exactes sont déterminantes, demandez-les avant de valider votre séjour.","Un grand lit double est confirmé ; les dimensions King Size restent à confirmer.",images.bed,[images.bed,images.entryAlt,images.entry],["Grand lit double confirmé","Literie haut de gamme","Dimensions King Size à confirmer"]],
 ["coin-cafe","Coin café","Coin café","Services","confirmed","Une pause chaude, à votre rythme.","Le coin café réunit machine à café, bouilloire, réfrigérateur, micro-ondes et grille-pain.","Vérifiez les consommables inclus et prévoyez vos préférences particulières si nécessaire.","Un espace dédié permet de préparer café, thé, petit-déjeuner ou collation.",images.entry,[images.entry,images.entryAlt,images.bed],["Machine à café","Bouilloire","Réfrigérateur et micro-ondes"]],
 ["champagne","Champagne","Champagne","Services","to-confirm","Une attention champenoise à demander avant le séjour.","La présence d’une bouteille de Champagne n’est pas confirmée comme inclusion standard.","Demandez les options disponibles et leur tarif ; ne conduisez jamais après consommation d’alcool.","Aucune bouteille incluse n’est garantie sans confirmation écrite.",images.entryAlt,[images.entryAlt,images.bed,images.bathMood],["Option à confirmer","Producteurs locaux à proximité","Consommation responsable"]],
 ["fauteuil-tantra","Fauteuil Tantra","Fauteuil Tantra","Ambiance","to-confirm","Un élément sensoriel dont la présence reste à valider.","L’univers de reconnexion d’Absolu ne constitue pas une prestation de tantra et la présence d’un fauteuil spécialisé n’est pas confirmée.","Demandez une photo et une confirmation explicite si cet élément est essentiel à votre réservation.","La présence et le modèle d’un fauteuil Tantra restent à confirmer.",images.entryAlt,[images.entryAlt,images.bed,images.entry],["Présence à confirmer","Aucune prestation Tantra","Suite réservée aux adultes responsables"]],
 ["ambiance-romantique","Ambiance romantique","Ambiance","Ambiance","confirmed","Deux atmosphères pour une même suite.","Lumière naturelle, matières sobres et ambiance colorée permettent d’adapter le décor à votre soirée.","Préparez une playlist et une attention personnelle plutôt que de surcharger l’espace.","L’ambiance lumineuse romantique fait partie de l’identité visuelle de la suite.",images.bathMood,[images.bathMood,images.saunaMood,images.bed],["Lumière modulable","Univers feutré","Espace entièrement privé"]],
 ["eclairage-led","Éclairage LED","Éclairage","Ambiance","confirmed","La lumière transforme les volumes.","L’éclairage d’ambiance coloré redessine la salle d’eau, le sauna et la douche après la tombée du jour.","Choisissez une intensité confortable et conservez un éclairage suffisant pour circuler en sécurité.","Un éclairage d’ambiance coloré est visible dans plusieurs espaces de la suite.",images.showerMood,[images.showerMood,images.bathMood,images.saunaMood],["Ambiance colorée","Plusieurs espaces éclairés","Contraste avec la lumière naturelle"]],
 ["douche-italienne","Douche à l’italienne","Douche","Bien-être","confirmed","Un espace d’eau aux lignes épurées.","La douche à l’italienne complète la baignoire balnéo et le sauna dans la salle de bains privative.","Utilisez-la entre deux temps de chaleur et laissez le sol dégagé après usage.","La douche à l’italienne se trouve dans la salle de bains réservée aux occupants.",images.shower,[images.shower,images.showerMood,images.bath],["Salle de bains privative","Douche à l’italienne","Ambiance naturelle ou colorée"]],
 ["peignoirs","Peignoirs","Peignoirs","Confort","confirmed","Prolonger la détente sans rupture.","Des peignoirs sont indiqués parmi les équipements de la suite.","Confirmez le nombre et les tailles disponibles si vous avez un besoin particulier.","Des peignoirs sont mis à disposition des occupants.",images.bath,[images.bath,images.sauna,images.bed],["Mis à disposition","Pratiques après le spa","Quantités selon occupation"]],
 ["serviettes","Serviettes","Serviettes","Confort","confirmed","Le linge utile à votre rituel d’eau.","Les serviettes font partie des équipements annoncés pour la salle de bains privative.","Utilisez une serviette sèche pour le sauna et suivez les consignes présentes dans la suite.","Des serviettes sont prévues pour les occupants de la suite.",images.shower,[images.shower,images.bath,images.sauna],["Fournies","Salle de bains privative","Usage spa et douche"]],
 ["penderie","Penderie","Penderie","Confort","confirmed","Ranger les effets, libérer l’espace.","La penderie permet d’organiser les vêtements et de conserver une suite dégagée.","Suspendez les tenues dès l’arrivée et gardez les objets de valeur avec vous.","Une penderie est indiquée dans l’inventaire de la suite.",images.entry,[images.entry,images.entryAlt,images.bed],["Rangement intégré","Espace nuit ordonné","Pratique pour les tenues"]],
 ["parking","Parking","Stationnement","Services","to-confirm","Préparer son arrivée sans supposer le stationnement.","Les modalités de parking ou de stationnement ne sont pas confirmées dans les informations actuelles.","Demandez où stationner légalement avant l’arrivée et ne bloquez jamais les accès riverains.","La disponibilité d’une place privée reste à confirmer.",images.entryAlt,[images.entryAlt,images.entry,images.bed],["Modalités à confirmer","Adresse à Avize","Accès de plain-pied indiqué"]],
 ["wifi","Wi-Fi","Wi-Fi","Services","confirmed","Rester connecté, ou choisir de décrocher.","Une connexion Wi-Fi gratuite est annoncée dans la Suite Absolu.","Téléchargez vos contenus importants avant le trajet et profitez aussi du séjour pour réduire les notifications.","Le Wi-Fi gratuit figure parmi les équipements confirmés.",images.bed,[images.bed,images.entry,images.entryAlt],["Connexion incluse","Usage privatif","Déconnexion volontaire possible"]],
 ["television","Télévision écran plat","Télévision","Confort","confirmed","Un écran pour une soirée choisie.","Une télévision à écran plat est disponible dans la suite.","Vérifiez vos accès personnels et déconnectez vos comptes avant le départ.","Une télévision écran plat est annoncée dans l’inventaire.",images.bed,[images.bed,images.entryAlt,images.entry],["Écran plat","Dans la suite","Comptes personnels à déconnecter"]],
 ["streaming","Streaming","Streaming","Services","to-confirm","Vos plateformes, selon la configuration disponible.","Le caractère connecté de la télévision ou l’accès natif aux plateformes de streaming n’est pas garanti.","Apportez vos identifiants si l’usage est possible, ne les partagez pas et déconnectez-vous au départ.","Les services et applications de streaming restent à confirmer.",images.bed,[images.bed,images.entry,images.entryAlt],["Applications à confirmer","Abonnements non garantis","Déconnexion des comptes recommandée"]],
] as const;
export const equipmentItems:EquipmentItem[]=raw.map(item=>({slug:item[0],name:item[1],shortName:item[2],category:item[3],status:item[4],headline:item[5],description:item[6],advice:item[7],detail:item[8],image:item[9],gallery:item[10],features:item[11],faq:faq(item[1],item[4],item[8])}));
export const getEquipment=(slug:string)=>equipmentItems.find(item=>item.slug===slug);
export const equipmentCategories=["Tous","Bien-être","Confort","Ambiance","Services"] as const;
