export type ArticleSection={id:string;title:string;paragraphs:readonly string[]};
export type MagazineArticle={slug:string;title:string;description:string;excerpt:string;category:string;tags:readonly string[];image:string;imageAlt:string;published:string;modified:string;author:string;sections:readonly ArticleSection[];faq:readonly {question:string;answer:string}[];readingTime:number;featured:boolean};
export const magazineAuthor={name:"La rédaction Absolu",role:"Guide de la Champagne romantique",description:"Une rédaction locale consacrée aux escapades à deux, au patrimoine champenois et à l’art de ralentir.",url:"/blog/auteur/redaction-absolu"} as const;
export const magazineCategories=["Love Rooms","Escapades","Champagne","Gastronomie","Conseils","Occasions","Bien-être","Saisons"] as const;
const imgs=["lit.webp","entree2.webp","salledebain.webp","sauna.webp","entree1.webp","salledebainviolet.webp","saunaviolet.webp","douche.webp","doucheviolet.webp"];
const slugify=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[’']/g,"-").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const faqFor=(title:string,place:string)=>[
 {question:`Comment préparer « ${title} » ?`,answer:`Commencez par vérifier les horaires officiels, limitez le programme à quelques étapes cohérentes et gardez du temps libre. Pour les caves, restaurants et activités à ${place}, la réservation directe auprès de chaque établissement reste recommandée.`},
 {question:"Quand venir en Champagne ?",answer:"Chaque saison possède son caractère. Le printemps et l’automne sont agréables pour marcher, l’été offre de longues soirées et l’hiver met en valeur les caves et les expériences bien-être. Les vendanges sont vivantes mais plus fréquentées."},
 {question:"Faut-il réserver les visites de caves ?",answer:"Oui, dans la majorité des cas. Les maisons et vignerons fixent leurs propres créneaux, langues, tarifs et conditions d’accueil. Vérifiez toujours leur site officiel avant le déplacement."},
 {question:"Comment organiser une dégustation responsable ?",answer:"Désignez un conducteur qui ne consomme pas d’alcool, utilisez un chauffeur ou choisissez une visite accessible sans voiture. L’abus d’alcool est dangereux pour la santé ; la dégustation n’est jamais obligatoire pour apprécier la Champagne."},
];
function sectionsFor(title:string,place:string,angle:string):ArticleSection[]{return[
 {id:"essentiel",title:`L’essentiel pour ${title.toLowerCase()}`,paragraphs:[`${title} mérite mieux qu’une liste d’adresses copiée à la hâte. Le bon point de départ consiste à comprendre le territoire, les distances et le rythme recherché. Autour de ${place}, le paysage champenois alterne villes, villages viticoles, coteaux et vallées. ${angle}. Une journée réussie ne cherche pas à tout couvrir : elle associe une découverte forte, un repas choisi et un temps sans programme.`,`Avant de partir, vérifiez les sources officielles. Les horaires saisonniers, travaux, vendanges et événements modifient parfois l’accès. Les maisons de champagne et de nombreux vignerons reçoivent sur réservation. Pour un séjour à deux, ajoutez une marge entre les étapes : elle protège la conversation et évite que la journée ressemble à une course.`]},
 {id:"itineraire",title:"Construire un itinéraire fluide",paragraphs:[`Placez l’étape la plus contrainte en premier : visite guidée, table réservée ou activité avec horaire fixe. Organisez ensuite les haltes libres autour de ce rendez-vous. Depuis ${place}, les routes touristiques conduisent vers des identités différentes : Côte des Blancs et chardonnay, vallée de la Marne et panoramas, montagne de Reims et forêt.`,`La conduite et la dégustation doivent être séparées. Désignez un conducteur sobre, réservez un professionnel ou limitez la journée à un secteur accessible. Les distances semblent courtes sur la carte, mais les routes de village et les arrêts panoramiques allongent naturellement le parcours. C’est une qualité si elle a été anticipée.`]},
 {id:"adresses",title:"Choisir des adresses avec discernement",paragraphs:[`Une recommandation éditoriale reste un point de départ, jamais une garantie. Cartes, équipes, tarifs et jours d’ouverture évoluent. Consultez le site de l’établissement, confirmez la réservation et signalez les contraintes alimentaires. À ${place}, privilégiez une adresse cohérente avec votre itinéraire plutôt qu’un détour dicté par une tendance.`,`Pour les restaurants romantiques, observez le niveau sonore, la durée du menu et la distance jusqu’au lieu de nuit. Pour les caves, comparez la durée, le contenu pédagogique et la taille des groupes. Une rencontre chez un vigneron indépendant et une visite de grande maison racontent deux dimensions complémentaires de la Champagne.`]},
 {id:"deux",title:"Préserver la dimension romantique",paragraphs:[`Le romantisme ne vient pas d’un décor automatique. Il apparaît lorsque le programme laisse de la place à l’attention. Pour ${title.toLowerCase()}, choisissez ensemble les grandes lignes et gardez éventuellement une petite surprise personnelle. Une lettre, une musique ou un arrêt lié à un souvenir vaut souvent mieux qu’une accumulation d’objets.`,`Acceptez aussi les changements de météo. Une averse peut conduire vers un musée, une cave ou un long déjeuner. Une fermeture imprévue peut devenir une promenade dans un autre village. Le séjour reste réussi lorsque l’objectif est de partager du temps, pas de valider une liste.`]},
 {id:"absolu",title:"Prolonger la journée chez Absolu",paragraphs:[`À Avize, la Suite Absolu offre un point d’ancrage sur la Côte des Blancs. Sa baignoire balnéo et son sauna infrarouge sont privatifs ; la douche à l’italienne, le grand lit double et le coin salon composent un espace indépendant. Après une journée autour de ${place}, l’intérêt est de ne plus dépendre d’horaires collectifs.`,`Réservez les activités avant l’arrivée, puis laissez la soirée respirer. Hydratez-vous, utilisez les équipements chauds avec mesure et respectez toute contre-indication personnelle. La lumière de la suite peut rester naturelle ou devenir plus enveloppante. Cette transition donne une conclusion simple au parcours : découvrir dehors, ralentir dedans.`]},
 {id:"pratique",title:"Repères pratiques et tourisme responsable",paragraphs:[`Respectez les parcelles : les vignes sont des espaces de travail privés. Restez sur les chemins autorisés, laissez passer les engins et ne cueillez pas de raisin. Pendant les vendanges, redoublez de prudence sur les petites routes. Emportez de l’eau, des chaussures adaptées et une couche supplémentaire pour les caves, souvent fraîches toute l’année.`,`Consultez les informations des offices de tourisme et du Comité Champagne pour préparer votre parcours. Les recommandations de ce magazine sont éditoriales et indépendantes. Elles doivent être vérifiées au moment du voyage. Cette méthode permet de profiter de ${place} avec curiosité, sécurité et respect des habitants.`]},
]}
const pillars=[
 ["meilleures-love-rooms-champagne","Les meilleures Love Rooms de Champagne","Love Rooms","Choisir une Love Room en Champagne : notre méthode et les critères qui comptent","spa privatif","Champagne","Un classement sérieux commence par les équipements réellement privatifs, la localisation, la transparence et la qualité du séjour, pas par des promesses invérifiables."],
 ["que-faire-epernay-en-amoureux","Que faire à Épernay en amoureux ?","Escapades","Que faire à Épernay en amoureux : itinéraire et idées à deux","Épernay en amoureux","Épernay","L’avenue de Champagne, le musée, les jardins et les coteaux permettent de composer une journée dense ou très lente."],
 ["visiter-avize","Visiter Avize : guide romantique de la Côte des Blancs","Champagne","Visiter Avize : vignes, promenade et bonnes idées sur la Côte des Blancs","Avize","Avize","Le parc Vix, les rues du village et les panoramas voisins racontent une Champagne à taille humaine."],
 ["caves-de-champagne","Les caves de Champagne : comprendre et préparer sa visite","Champagne","Caves de Champagne : comment choisir et préparer une visite","caves","Champagne","Crayères rémoises, caves d’Épernay et domaines de vignerons offrent des expériences différentes qu’il est utile de comparer."],
 ["route-touristique-champagne","Route touristique du Champagne : itinéraires et conseils","Champagne","Route touristique du Champagne : circuits, étapes et conseils","route touristique","Épernay","La Côte des Blancs, la vallée de la Marne et la montagne de Reims demandent chacune du temps et un itinéraire distinct."],
 ["restaurant-romantique-champagne","Restaurant romantique en Champagne : choisir la bonne table","Gastronomie","Restaurant romantique en Champagne : nos critères et adresses à explorer","restaurant romantique","Épernay","Une table en tête-à-tête se choisit selon l’ambiance, la cuisine, le trajet et la place qu’elle laisse au reste de la soirée."],
 ["organiser-demande-en-mariage","Organiser une demande en mariage intime et mémorable","Occasions","Organiser une demande en mariage en Champagne : guide complet","demande en mariage","Avize","Une demande réussie respecte la personnalité du couple, la liberté de réponse et un plan assez simple pour rester sincère."],
 ["comment-surprendre-partenaire","Comment surprendre son partenaire avec justesse ?","Conseils","Comment surprendre son partenaire : idées romantiques et conseils","surprise romantique","Champagne","La meilleure surprise est personnelle, confortable pour l’autre et fondée sur un détail réel de votre histoire."],
 ["champagne-sous-la-pluie","Que faire en Champagne sous la pluie ?","Saisons","Que faire en Champagne sous la pluie : idées à Épernay et autour","pluie","Épernay","Caves, musées, patrimoine et longues tables transforment facilement une météo humide en journée réussie."],
 ["plus-beaux-villages-champagne","Les plus beaux villages de Champagne à découvrir à deux","Champagne","Plus beaux villages de Champagne : itinéraire romantique","villages","Champagne","Avize, Cramant, Hautvillers, Aÿ-Champagne et d’autres villages révèlent des paysages et patrimoines très différents."],
] as const;
const pillarArticles:MagazineArticle[]=pillars.map((p,index)=>({slug:p[0],title:p[1],category:p[2],description:p[3],excerpt:p[6],tags:[p[4],p[5],"séjour romantique"],image:`/images/optimized/${imgs[index%imgs.length]}`,imageAlt:`Illustration de l’article ${p[1]}`,published:"2026-08-03",modified:"2026-08-03",author:magazineAuthor.name,sections:sectionsFor(p[1],p[5],p[6]),faq:faqFor(p[1],p[5]),readingTime:9,featured:true}));
const subjects=["une journée sans voiture","un week-end de printemps","une escapade d’automne","une parenthèse hivernale","un séjour gourmand","une balade photographique","une découverte du chardonnay","un itinéraire bien-être","une surprise d’anniversaire","un séjour de deux nuits","une escapade responsable","un premier voyage en Champagne"];
const categoryPlans=[
 ["Love Rooms","Bien choisir sa Love Room pour","équipements privatifs"],["Escapades","Notre guide pour","itinéraire romantique"],["Champagne","Comprendre la Champagne à travers","vignoble"],["Gastronomie","Accords et bonnes tables pour","gastronomie"],["Conseils","Conseils pratiques pour","organisation"],["Occasions","Célébrer à deux avec","célébration"],["Bien-être","Ralentir ensemble grâce à","bien-être"],["Saisons","Vivre la Champagne avec","saisons"],
] as const;
const generated:MagazineArticle[]=categoryPlans.flatMap((plan,categoryIndex)=>subjects.map((subject,subjectIndex)=>{const title=`${plan[1]} ${subject}`;const place=["Avize","Épernay","Côte des Blancs","vallée de la Marne"][subjectIndex%4];const angle=`Ce dossier relie ${subject} aux réalités du terrain, avec des choix sobres, des vérifications utiles et un rythme adapté au couple`;return{slug:slugify(`${plan[0]}-${subject}`),title,category:plan[0],description:`${title} : itinéraire, conseils locaux et idées pour préparer une expérience à deux autour d’Avize et d’Épernay.`,excerpt:`${angle}.`,tags:[plan[2],subject,place],image:`/images/optimized/${imgs[(categoryIndex+subjectIndex)%imgs.length]}`,imageAlt:`Magazine Absolu : ${subject} en Champagne`,published:"2026-08-03",modified:"2026-08-03",author:magazineAuthor.name,sections:sectionsFor(title,place,angle),faq:faqFor(title,place),readingTime:8+(subjectIndex%3),featured:false}}));
export const magazineArticles=[...pillarArticles,...generated];
export const getMagazineArticle=(slug:string)=>magazineArticles.find(article=>article.slug===slug);
export const magazineTags=[...new Set(magazineArticles.flatMap(article=>article.tags))].sort((a,b)=>a.localeCompare(b,"fr"));
export const relatedArticles=(article:MagazineArticle,limit=3)=>magazineArticles.filter(candidate=>candidate.slug!==article.slug).map(candidate=>({candidate,score:(candidate.category===article.category?3:0)+candidate.tags.filter(tag=>article.tags.includes(tag)).length})).sort((a,b)=>b.score-a.score).slice(0,limit).map(({candidate})=>candidate);
