import type { Locale } from "@/lib/i18n/config";

export type VisualCategory = "suite" | "balneo" | "sauna" | "ambiance" | "equipment";
export type VisualImage = { src:string; alt:string; caption:string; categories:VisualCategory[]; orientation:"wide"|"portrait" };
type Copy = { all:string; categories:Record<VisualCategory,string>; categoryLabel:string; open:string; close:string; previous:string; next:string; viewer:string; suiteEyebrow:string; suiteTitle:string; suiteIntro:string; galleryEyebrow:string; galleryTitle:string; galleryIntro:string; sections:{eyebrow:string;title:string;body:string}[]; ctaMid:string; ctaFinal:string; galleryCtaTitle:string; availability:string; mosaicEyebrow:string; mosaicTitle:string };

const baseSections: Record<Locale, Copy["sections"]> = {
 fr:[{eyebrow:"La suite",title:"Un cocon privé à Avize",body:"Une entrée indépendante, un espace de plain-pied et des matières chaleureuses pour s’installer à son rythme, loin des espaces partagés."},{eyebrow:"La baignoire balnéo",title:"Un moment suspendu",body:"La baignoire balnéo privative invite à retrouver la chaleur, le calme et le plaisir simple de ne plus regarder l’heure."},{eyebrow:"Le sauna infrarouge",title:"Une chaleur douce et privée",body:"Intégré à la suite, le sauna prolonge la parenthèse bien-être sans créneau ni déplacement."},{eyebrow:"Une nuit à deux",title:"Se retrouver, simplement",body:"Le grand lit double, le coin salon et la lumière modulable composent un refuge calme après une journée dans les vignes."},{eyebrow:"Tout le nécessaire sur place",title:"Le matin peut attendre",body:"Réfrigérateur, micro-ondes, bouilloire, grille-pain et coin café permettent de savourer une collation sans quitter le cocon."}],
 en:[{eyebrow:"The suite",title:"A private retreat in Avize",body:"A separate entrance, ground-floor layout and warm materials let you settle in at your own pace, away from shared spaces."},{eyebrow:"The whirlpool bath",title:"A moment out of time",body:"The private whirlpool bath invites you to enjoy warmth, quiet and the simple pleasure of forgetting the clock."},{eyebrow:"The infrared sauna",title:"Gentle, private warmth",body:"Built into the suite, the sauna extends your wellness moment with no appointments or travel."},{eyebrow:"A night for two",title:"Time together, simply",body:"The large double bed, lounge area and adjustable lighting create a quiet haven after a day among the vineyards."},{eyebrow:"Everything close at hand",title:"Morning can wait",body:"A fridge, microwave, kettle, toaster and coffee corner make it easy to enjoy a snack without leaving your retreat."}],
 de:[{eyebrow:"Die Suite",title:"Ein privater Rückzugsort in Avize",body:"Separater Eingang, ebenerdige Räume und warme Materialien lassen Sie fern von Gemeinschaftsbereichen in Ruhe ankommen."},{eyebrow:"Die Whirlpool-Badewanne",title:"Ein schwebender Moment",body:"Die private Whirlpool-Badewanne lädt zu Wärme, Ruhe und gemeinsamer Zeit ein."},{eyebrow:"Die Infrarotsauna",title:"Sanfte, private Wärme",body:"Die Sauna ist in die Suite integriert und verlängert die Wellnesspause ohne Termin oder Weg."},{eyebrow:"Eine Nacht zu zweit",title:"Einfach zusammen sein",body:"Doppelbett, Sitzecke und regulierbares Licht schaffen einen stillen Rückzugsort nach einem Tag in den Weinbergen."},{eyebrow:"Alles vor Ort",title:"Der Morgen kann warten",body:"Kühlschrank, Mikrowelle, Wasserkocher, Toaster und Kaffeeecke sorgen für Komfort im eigenen Kokon."}],
 nl:[{eyebrow:"De suite",title:"Een privéplek in Avize",body:"Een eigen ingang, gelijkvloerse indeling en warme materialen laten jullie in alle rust aankomen."},{eyebrow:"Het bubbelbad",title:"Even buiten de tijd",body:"Het privébubbelbad nodigt uit tot warmte, stilte en tijd samen."},{eyebrow:"De infraroodsauna",title:"Zachte warmte in alle privacy",body:"De sauna ligt in de suite en verlengt het wellnessmoment zonder afspraak of verplaatsing."},{eyebrow:"Een nacht met z’n tweeën",title:"Gewoon samen zijn",body:"Het grote bed, de zithoek en regelbare verlichting vormen een rustig toevluchtsoord."},{eyebrow:"Alles bij de hand",title:"De ochtend kan wachten",body:"Koelkast, magnetron, waterkoker, broodrooster en koffiehoek bieden comfort zonder de suite te verlaten."}],
 it:[{eyebrow:"La suite",title:"Un rifugio privato ad Avize",body:"Ingresso indipendente, spazi al piano terra e materiali caldi per arrivare con calma, lontano dagli spazi condivisi."},{eyebrow:"La vasca idromassaggio",title:"Un momento sospeso",body:"La vasca privata invita al calore, al silenzio e al piacere di dimenticare l’ora."},{eyebrow:"La sauna a infrarossi",title:"Calore dolce e privato",body:"Integrata nella suite, la sauna prolunga il benessere senza orari né spostamenti."},{eyebrow:"Una notte in due",title:"Ritrovarsi, semplicemente",body:"Il grande letto, il salottino e la luce regolabile creano un rifugio tranquillo."},{eyebrow:"Tutto a portata di mano",title:"Il mattino può attendere",body:"Frigorifero, microonde, bollitore, tostapane e angolo caffè rendono il soggiorno autonomo."}],
 es:[{eyebrow:"La suite",title:"Un refugio privado en Avize",body:"Entrada independiente, distribución en planta baja y materiales cálidos para llegar con calma."},{eyebrow:"La bañera de hidromasaje",title:"Un momento suspendido",body:"La bañera privada invita al calor, al silencio y al placer de olvidarse del reloj."},{eyebrow:"La sauna de infrarrojos",title:"Calor suave y privado",body:"Integrada en la suite, la sauna prolonga el bienestar sin horarios ni desplazamientos."},{eyebrow:"Una noche para dos",title:"Reencontrarse, sencillamente",body:"La cama doble, el salón y la luz regulable crean un refugio tranquilo."},{eyebrow:"Todo a mano",title:"La mañana puede esperar",body:"Nevera, microondas, hervidor, tostadora y rincón de café ofrecen autonomía dentro de la suite."}],
 pt:[{eyebrow:"A suite",title:"Um refúgio privativo em Avize",body:"Entrada independente, piso térreo e materiais acolhedores para chegar com calma, longe de espaços partilhados."},{eyebrow:"A banheira de hidromassagem",title:"Um momento suspenso",body:"A banheira privativa convida ao calor, ao silêncio e ao prazer de esquecer as horas."},{eyebrow:"A sauna de infravermelhos",title:"Calor suave e privativo",body:"Integrada na suite, a sauna prolonga o bem-estar sem horários nem deslocações."},{eyebrow:"Uma noite a dois",title:"Estar juntos, simplesmente",body:"A cama de casal, a zona de estar e a luz regulável criam um refúgio tranquilo."},{eyebrow:"Tudo à mão",title:"A manhã pode esperar",body:"Frigorífico, micro-ondas, chaleira, torradeira e zona de café oferecem autonomia na suite."}],
};

const concise: Record<Locale, Omit<Copy,"sections">> = {
 fr:{all:"Tout",categories:{suite:"Suite",balneo:"Balnéo",sauna:"Sauna",ambiance:"Ambiance",equipment:"Équipements"},categoryLabel:"Catégories de la galerie",open:"Agrandir",close:"Fermer la visionneuse",previous:"Photo précédente",next:"Photo suivante",viewer:"Visionneuse plein écran",suiteEyebrow:"Une expérience pensée pour deux",suiteTitle:"La suite, rien que pour vous",suiteIntro:"À Avize, Absolu réunit dans un cocon privé de 35 m² un grand lit double, une baignoire balnéo et un sauna infrarouge. Entrez, ralentissez, profitez.",galleryEyebrow:"Une parenthèse en images",galleryTitle:"Galerie de la Suite Absolu",galleryIntro:"Découvrez les espaces réels d’Absolu, de la lumière naturelle aux nuances plus intimes du soir.",ctaMid:"Vérifier les disponibilités",ctaFinal:"Réserver votre séjour",galleryCtaTitle:"Cette expérience vous attend à Avize",availability:"Voir les disponibilités",mosaicEyebrow:"Ambiance et détails",mosaicTitle:"Du jour feutré aux reflets du soir"},
 en:{all:"All",categories:{suite:"Suite",balneo:"Whirlpool bath",sauna:"Sauna",ambiance:"Atmosphere",equipment:"Facilities"},categoryLabel:"Gallery categories",open:"Enlarge",close:"Close viewer",previous:"Previous photo",next:"Next photo",viewer:"Full-screen viewer",suiteEyebrow:"An experience designed for two",suiteTitle:"The suite, all to yourselves",suiteIntro:"In Avize, Absolu brings together a large double bed, a whirlpool bath and an infrared sauna in one private 35 m² retreat.",galleryEyebrow:"A story told in images",galleryTitle:"Absolu Suite gallery",galleryIntro:"Explore the real spaces at Absolu, from soft daylight to the more intimate colours of evening.",ctaMid:"Check availability",ctaFinal:"Book your stay",galleryCtaTitle:"This experience awaits you in Avize",availability:"View availability",mosaicEyebrow:"Atmosphere and details",mosaicTitle:"From soft daylight to evening glow"},
 de:{all:"Alle",categories:{suite:"Suite",balneo:"Whirlpool",sauna:"Sauna",ambiance:"Atmosphäre",equipment:"Ausstattung"},categoryLabel:"Galeriekategorien",open:"Vergrößern",close:"Bildansicht schließen",previous:"Vorheriges Foto",next:"Nächstes Foto",viewer:"Vollbildansicht",suiteEyebrow:"Ein Erlebnis für zwei",suiteTitle:"Die Suite, ganz für Sie",suiteIntro:"In Avize vereint Absolu auf 35 m² ein großes Doppelbett, eine Whirlpool-Badewanne und eine Infrarotsauna in einem privaten Rückzugsort.",galleryEyebrow:"Eine Auszeit in Bildern",galleryTitle:"Galerie der Suite Absolu",galleryIntro:"Entdecken Sie die echten Räume von Absolu – vom sanften Tageslicht bis zur intimen Abendstimmung.",ctaMid:"Verfügbarkeit prüfen",ctaFinal:"Aufenthalt buchen",galleryCtaTitle:"Dieses Erlebnis erwartet Sie in Avize",availability:"Verfügbarkeit ansehen",mosaicEyebrow:"Atmosphäre und Details",mosaicTitle:"Vom sanften Tag zum Abendlicht"},
 nl:{all:"Alles",categories:{suite:"Suite",balneo:"Bubbelbad",sauna:"Sauna",ambiance:"Sfeer",equipment:"Voorzieningen"},categoryLabel:"Galeriecategorieën",open:"Vergroten",close:"Viewer sluiten",previous:"Vorige foto",next:"Volgende foto",viewer:"Viewer op volledig scherm",suiteEyebrow:"Een ervaring voor twee",suiteTitle:"De suite, helemaal voor jullie",suiteIntro:"In Avize combineert Absolu op 35 m² een groot tweepersoonsbed, een privébubbelbad en een infraroodsauna.",galleryEyebrow:"Een verblijf in beelden",galleryTitle:"Galerij van Suite Absolu",galleryIntro:"Ontdek de echte ruimtes van Absolu, van zacht daglicht tot de intieme kleuren van de avond.",ctaMid:"Beschikbaarheid bekijken",ctaFinal:"Boek jullie verblijf",galleryCtaTitle:"Deze ervaring wacht op jullie in Avize",availability:"Beschikbaarheid bekijken",mosaicEyebrow:"Sfeer en details",mosaicTitle:"Van zacht daglicht tot avondgloed"},
 it:{all:"Tutto",categories:{suite:"Suite",balneo:"Idromassaggio",sauna:"Sauna",ambiance:"Atmosfera",equipment:"Dotazioni"},categoryLabel:"Categorie della galleria",open:"Ingrandisci",close:"Chiudi la galleria",previous:"Foto precedente",next:"Foto successiva",viewer:"Galleria a schermo intero",suiteEyebrow:"Un’esperienza pensata per due",suiteTitle:"La suite, tutta per voi",suiteIntro:"Ad Avize, Absolu riunisce in 35 m² privati un grande letto matrimoniale, una vasca idromassaggio e una sauna a infrarossi.",galleryEyebrow:"Una parentesi per immagini",galleryTitle:"Galleria della Suite Absolu",galleryIntro:"Scoprite gli spazi reali di Absolu, dalla luce naturale alle tonalità intime della sera.",ctaMid:"Verifica la disponibilità",ctaFinal:"Prenota il soggiorno",galleryCtaTitle:"Questa esperienza vi aspetta ad Avize",availability:"Vedi disponibilità",mosaicEyebrow:"Atmosfera e dettagli",mosaicTitle:"Dal giorno soffuso ai riflessi serali"},
 es:{all:"Todo",categories:{suite:"Suite",balneo:"Hidromasaje",sauna:"Sauna",ambiance:"Ambiente",equipment:"Equipamiento"},categoryLabel:"Categorías de la galería",open:"Ampliar",close:"Cerrar la galería",previous:"Foto anterior",next:"Foto siguiente",viewer:"Galería a pantalla completa",suiteEyebrow:"Una experiencia para dos",suiteTitle:"La suite, solo para vosotros",suiteIntro:"En Avize, Absolu reúne en 35 m² privados una gran cama doble, una bañera de hidromasaje y una sauna de infrarrojos.",galleryEyebrow:"Un paréntesis en imágenes",galleryTitle:"Galería de la Suite Absolu",galleryIntro:"Descubrid los espacios reales de Absolu, desde la luz natural hasta los tonos íntimos de la noche.",ctaMid:"Comprobar disponibilidad",ctaFinal:"Reservar vuestra estancia",galleryCtaTitle:"Esta experiencia os espera en Avize",availability:"Ver disponibilidad",mosaicEyebrow:"Ambiente y detalles",mosaicTitle:"De la luz suave al brillo nocturno"},
 pt:{all:"Tudo",categories:{suite:"Suite",balneo:"Hidromassagem",sauna:"Sauna",ambiance:"Ambiente",equipment:"Equipamentos"},categoryLabel:"Categorias da galeria",open:"Ampliar",close:"Fechar a galeria",previous:"Foto anterior",next:"Foto seguinte",viewer:"Galeria em ecrã inteiro",suiteEyebrow:"Uma experiência para dois",suiteTitle:"A suite, só para vocês",suiteIntro:"Em Avize, Absolu reúne em 35 m² privativos uma grande cama de casal, uma banheira de hidromassagem e uma sauna de infravermelhos.",galleryEyebrow:"Uma pausa em imagens",galleryTitle:"Galeria da Suite Absolu",galleryIntro:"Descubram os espaços reais de Absolu, da luz natural aos tons íntimos da noite.",ctaMid:"Verificar disponibilidade",ctaFinal:"Reservar a estadia",galleryCtaTitle:"Esta experiência espera por vocês em Avize",availability:"Ver disponibilidade",mosaicEyebrow:"Ambiente e detalhes",mosaicTitle:"Da luz suave ao brilho da noite"},
};

const genericImageText: Record<Locale,{bed:string;room:string;kitchen:string;balneo:string;balneoNight:string;sauna:string;saunaNight:string;shower:string;showerNight:string}> = {
 fr:{bed:"Lit double de la Suite Absolu avec éclairage romantique à Avize",room:"Vue générale de la Suite Absolu et de son coin café",kitchen:"Entrée et kitchenette de la Suite Absolu à Avize",balneo:"Baignoire balnéo privative de la Love Room Absolu",balneoNight:"Baignoire balnéo privative sous un éclairage violet",sauna:"Sauna infrarouge privatif de la suite Absolu à Avize",saunaNight:"Sauna privatif de la Suite Absolu en ambiance violette",shower:"Douche à l’italienne de la Suite Absolu",showerNight:"Douche à l’italienne sous l’éclairage d’ambiance"},
 en:{bed:"Double bed in the Absolu romantic suite in Avize",room:"Wide view of the Absolu Suite and coffee corner",kitchen:"Entrance and kitchenette in the Absolu Suite",balneo:"Private whirlpool bath in the Absolu Love Room",balneoNight:"Private whirlpool bath under violet lighting",sauna:"Private infrared sauna in the Absolu Suite in Avize",saunaNight:"Private sauna in the Absolu Suite under violet light",shower:"Walk-in shower in the Absolu Suite",showerNight:"Walk-in shower under ambient lighting"},
 de:{bed:"Doppelbett der romantischen Suite Absolu in Avize",room:"Gesamtansicht der Suite Absolu mit Kaffeeecke",kitchen:"Eingang und Küchenzeile der Suite Absolu",balneo:"Private Whirlpool-Badewanne der Love Room Absolu",balneoNight:"Private Whirlpool-Badewanne in violettem Licht",sauna:"Private Infrarotsauna der Suite Absolu in Avize",saunaNight:"Private Sauna der Suite Absolu in violettem Licht",shower:"Bodengleiche Dusche der Suite Absolu",showerNight:"Bodengleiche Dusche mit Stimmungslicht"},
 nl:{bed:"Tweepersoonsbed in de romantische Suite Absolu in Avize",room:"Overzicht van Suite Absolu en de koffiehoek",kitchen:"Entree en kitchenette van Suite Absolu",balneo:"Privébubbelbad in Love Room Absolu",balneoNight:"Privébubbelbad onder violet licht",sauna:"Privé-infraroodsauna in Suite Absolu in Avize",saunaNight:"Privésauna van Suite Absolu in violet licht",shower:"Inloopdouche in Suite Absolu",showerNight:"Inloopdouche met sfeerverlichting"},
 it:{bed:"Letto matrimoniale della Suite romantica Absolu ad Avize",room:"Vista generale della Suite Absolu e angolo caffè",kitchen:"Ingresso e angolo cottura della Suite Absolu",balneo:"Vasca idromassaggio privata della Love Room Absolu",balneoNight:"Vasca idromassaggio privata sotto luce viola",sauna:"Sauna a infrarossi privata della Suite Absolu ad Avize",saunaNight:"Sauna privata della Suite Absolu con luce viola",shower:"Doccia walk-in della Suite Absolu",showerNight:"Doccia walk-in con illuminazione d’atmosfera"},
 es:{bed:"Cama doble de la Suite romántica Absolu en Avize",room:"Vista general de la Suite Absolu y rincón de café",kitchen:"Entrada y cocina de la Suite Absolu",balneo:"Bañera de hidromasaje privada de Love Room Absolu",balneoNight:"Bañera de hidromasaje privada bajo luz violeta",sauna:"Sauna de infrarrojos privada de la Suite Absolu en Avize",saunaNight:"Sauna privada de la Suite Absolu con luz violeta",shower:"Ducha italiana de la Suite Absolu",showerNight:"Ducha italiana con iluminación ambiental"},
 pt:{bed:"Cama de casal da Suite romântica Absolu em Avize",room:"Vista geral da Suite Absolu e zona de café",kitchen:"Entrada e kitchenette da Suite Absolu",balneo:"Banheira de hidromassagem privativa da Love Room Absolu",balneoNight:"Banheira de hidromassagem privativa sob luz violeta",sauna:"Sauna de infravermelhos privativa da Suite Absolu em Avize",saunaNight:"Sauna privativa da Suite Absolu com luz violeta",shower:"Duche italiano da Suite Absolu",showerNight:"Duche italiano com iluminação ambiente"},
};
const files:Array<[keyof typeof genericImageText.fr,string,VisualCategory[],"wide"|"portrait"]>=[["bed","lit",["suite","ambiance"],"wide"],["room","entree1",["suite","equipment"],"wide"],["kitchen","entree2",["suite","equipment"],"portrait"],["balneo","salledebain",["balneo","equipment"],"wide"],["balneoNight","salledebainviolet",["balneo","ambiance"],"wide"],["sauna","sauna",["sauna","equipment"],"portrait"],["saunaNight","saunaviolet",["sauna","ambiance"],"portrait"],["shower","douche",["equipment"],"portrait"],["showerNight","doucheviolet",["ambiance","equipment"],"portrait"]];
export function getVisualContent(locale:Locale){const copy={...concise[locale],sections:baseSections[locale]};return{copy,images:files.map(([key,file,categories,orientation])=>({src:`/images/optimized/${file}.webp`,alt:genericImageText[locale][key],caption:genericImageText[locale][key],categories,orientation})) satisfies VisualImage[]}}
