import "server-only";
import { createAdminClient } from "@/lib/supabase/admin";
import { sendGuestCommunication } from "@/lib/email";
import { siteConfig } from "@/lib/site-config";
import { communicationWindowOpen } from "./eligibility";
import { getGuestExperienceSettings } from "./settings";
import { ensureGuestPortalToken } from "./repository";
import type { CommunicationType } from "./types";

const validGuestEmail=(email:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)&&!email.toLowerCase().endsWith("@invalid.local");
type ReservationRow={id:string;reference:string;guest_first_name:string;guest_email:string;guest_count:number;check_in:string;check_out:string;total:number;status:string;payment_status:string;source:string;guest_portal_token:string|null;reservation_options:Array<{label:string}>};
export function communicationIsDue(type:Exclude<CommunicationType,"confirmation">,r:ReservationRow,now:Date,revealTime="14:00") {return communicationWindowOpen({type,checkIn:r.check_in,checkOut:r.check_out,now,revealTime})}
export async function queueConfirmation(reservationId:string){const token=await ensureGuestPortalToken(reservationId);const {error}=await createAdminClient().from("reservation_communications").upsert({reservation_id:reservationId,type:"confirmation",channel:"email",status:"pending",scheduled_for:new Date().toISOString()},{onConflict:"reservation_id,type",ignoreDuplicates:true});if(error)throw error;return token}
export async function processGuestCommunications(now=new Date(),only?:{reservationId:string;type:CommunicationType;force?:boolean}){
 const db=createAdminClient(),settings=await getGuestExperienceSettings();let query=db.from("reservations").select("id,reference,guest_first_name,guest_email,guest_count,check_in,check_out,total,status,payment_status,source,guest_portal_token,reservation_options(label)");if(only)query=query.eq("id",only.reservationId);const{data,error}=await query;if(error)throw error;const results=[];
 for(const r of (data??[]) as ReservationRow[]){if(r.status!=="confirmed"||(r.source==="direct"&&!['paid','partially_refunded'].includes(r.payment_status))||!validGuestEmail(r.guest_email))continue;const types:CommunicationType[]=only?[only.type]:['confirmation','pre_arrival','access_ready','checkout_reminder','post_stay_review'];for(const type of types){const reveal=settings.keyboxRevealTime;if(type!=='confirmation'&&!only&&!communicationIsDue(type,r,now,reveal))continue;if(type==='post_stay_review'&&!settings.googleReviewUrl){}const token=r.guest_portal_token??await ensureGuestPortalToken(r.id);if(type!=='confirmation'||only)await db.from("reservation_communications").upsert({reservation_id:r.id,type,channel:'email',status:'pending',scheduled_for:now.toISOString()},{onConflict:'reservation_id,type',ignoreDuplicates:true});let claim=db.from("reservation_communications").update({status:'processing',updated_at:now.toISOString()}).eq('reservation_id',r.id).eq('type',type);if(!only?.force)claim=claim.is('sent_at',null).in('status',['pending','failed']);const{data:claimed}=await claim.select('id,attempt_count').maybeSingle();if(!claimed)continue;
 try{const providerId=await sendGuestCommunication({type,firstName:r.guest_first_name,checkIn:r.check_in,checkOut:r.check_out,guestCount:r.guest_count,total:r.total,address:settings.address,portalUrl:`${siteConfig.url}/mon-sejour/${token}`,checkInTime:settings.checkInTime,checkOutTime:settings.checkOutTime,options:(r.reservation_options??[]).map(o=>o.label),checkoutInstructions:settings.checkoutInstructions,googleReviewUrl:settings.googleReviewUrl},r.guest_email);await db.from('reservation_communications').update({status:'sent',sent_at:now.toISOString(),provider_message_id:providerId,error:null,attempt_count:claimed.attempt_count+1,updated_at:now.toISOString()}).eq('id',claimed.id);results.push({reservationId:r.id,type,status:'sent'});}catch(e){await db.from('reservation_communications').update({status:'failed',error:e instanceof Error?e.message.slice(0,500):'UNKNOWN',attempt_count:claimed.attempt_count+1,updated_at:now.toISOString()}).eq('id',claimed.id);results.push({reservationId:r.id,type,status:'failed'});}
 }}return results;
}
